/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as MagicLinkRouteImport } from './routes/magic-link'
import { Route as AccessCodeRouteImport } from './routes/access-code'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as VTokenRouteImport } from './routes/v/$token'
import { Route as ServiceOrderAccessTokenRouteImport } from './routes/service-order-access/$token'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedServiceOrdersRouteRouteImport } from './routes/_authenticated/service-orders/route'
import { Route as AuthenticatedRequestsRouteRouteImport } from './routes/_authenticated/requests/route'
import { Route as AuthenticatedAssetsRouteRouteImport } from './routes/_authenticated/assets/route'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedServiceOrdersIndexRouteImport } from './routes/_authenticated/service-orders/index'
import { Route as AuthenticatedRequestsIndexRouteImport } from './routes/_authenticated/requests/index'
import { Route as AuthenticatedReliabilityIndexRouteImport } from './routes/_authenticated/reliability/index'
import { Route as AuthenticatedOutOfToleranceIndexRouteImport } from './routes/_authenticated/out-of-tolerance/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedCertificatesIndexRouteImport } from './routes/_authenticated/certificates/index'
import { Route as AuthenticatedCalendarIndexRouteImport } from './routes/_authenticated/calendar/index'
import { Route as AuthenticatedAssetsIndexRouteImport } from './routes/_authenticated/assets/index'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings/profile'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedServiceOrdersIdRouteImport } from './routes/_authenticated/service-orders/$id'
import { Route as AuthenticatedRequestsNewRouteImport } from './routes/_authenticated/requests/new'
import { Route as AuthenticatedRequestsIdRouteImport } from './routes/_authenticated/requests/$id'
import { Route as AuthenticatedCertificatesIdRouteImport } from './routes/_authenticated/certificates/$id'
import { Route as AuthenticatedAssetsIdRouteImport } from './routes/_authenticated/assets/$id'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const MagicLinkRoute = MagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessCodeRoute = AccessCodeRouteImport.update({
  id: '/access-code',
  path: '/access-code',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const VTokenRoute = VTokenRouteImport.update({
  id: '/v/$token',
  path: '/v/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceOrderAccessTokenRoute = ServiceOrderAccessTokenRouteImport.update({
  id: '/service-order-access/$token',
  path: '/service-order-access/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServiceOrdersRouteRoute =
  AuthenticatedServiceOrdersRouteRouteImport.update({
    id: '/service-orders',
    path: '/service-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRequestsRouteRoute =
  AuthenticatedRequestsRouteRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssetsRouteRoute =
  AuthenticatedAssetsRouteRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedServiceOrdersIndexRoute =
  AuthenticatedServiceOrdersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedServiceOrdersRouteRoute,
  } as any)
const AuthenticatedRequestsIndexRoute =
  AuthenticatedRequestsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRequestsRouteRoute,
  } as any)
const AuthenticatedReliabilityIndexRoute =
  AuthenticatedReliabilityIndexRouteImport.update({
    id: '/reliability/',
    path: '/reliability/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOutOfToleranceIndexRoute =
  AuthenticatedOutOfToleranceIndexRouteImport.update({
    id: '/out-of-tolerance/',
    path: '/out-of-tolerance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCertificatesIndexRoute =
  AuthenticatedCertificatesIndexRouteImport.update({
    id: '/certificates/',
    path: '/certificates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarIndexRoute =
  AuthenticatedCalendarIndexRouteImport.update({
    id: '/calendar/',
    path: '/calendar/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssetsIndexRoute =
  AuthenticatedAssetsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAssetsRouteRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedServiceOrdersIdRoute =
  AuthenticatedServiceOrdersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedServiceOrdersRouteRoute,
  } as any)
const AuthenticatedRequestsNewRoute =
  AuthenticatedRequestsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedRequestsRouteRoute,
  } as any)
const AuthenticatedRequestsIdRoute = AuthenticatedRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedRequestsRouteRoute,
} as any)
const AuthenticatedCertificatesIdRoute =
  AuthenticatedCertificatesIdRouteImport.update({
    id: '/certificates/$id',
    path: '/certificates/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssetsIdRoute = AuthenticatedAssetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAssetsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/access-code': typeof AccessCodeRoute
  '/magic-link': typeof MagicLinkRoute
  '/sign-in': typeof SignInRoute
  '/assets': typeof AuthenticatedAssetsRouteRouteWithChildren
  '/requests': typeof AuthenticatedRequestsRouteRouteWithChildren
  '/service-orders': typeof AuthenticatedServiceOrdersRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/service-order-access/$token': typeof ServiceOrderAccessTokenRoute
  '/v/$token': typeof VTokenRoute
  '/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/certificates/$id': typeof AuthenticatedCertificatesIdRoute
  '/requests/$id': typeof AuthenticatedRequestsIdRoute
  '/requests/new': typeof AuthenticatedRequestsNewRoute
  '/service-orders/$id': typeof AuthenticatedServiceOrdersIdRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/assets/': typeof AuthenticatedAssetsIndexRoute
  '/calendar/': typeof AuthenticatedCalendarIndexRoute
  '/certificates/': typeof AuthenticatedCertificatesIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/out-of-tolerance/': typeof AuthenticatedOutOfToleranceIndexRoute
  '/reliability/': typeof AuthenticatedReliabilityIndexRoute
  '/requests/': typeof AuthenticatedRequestsIndexRoute
  '/service-orders/': typeof AuthenticatedServiceOrdersIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/accept-invite': typeof AcceptInviteRoute
  '/access-code': typeof AccessCodeRoute
  '/magic-link': typeof MagicLinkRoute
  '/sign-in': typeof SignInRoute
  '/service-order-access/$token': typeof ServiceOrderAccessTokenRoute
  '/v/$token': typeof VTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/certificates/$id': typeof AuthenticatedCertificatesIdRoute
  '/requests/$id': typeof AuthenticatedRequestsIdRoute
  '/requests/new': typeof AuthenticatedRequestsNewRoute
  '/service-orders/$id': typeof AuthenticatedServiceOrdersIdRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/assets': typeof AuthenticatedAssetsIndexRoute
  '/calendar': typeof AuthenticatedCalendarIndexRoute
  '/certificates': typeof AuthenticatedCertificatesIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/out-of-tolerance': typeof AuthenticatedOutOfToleranceIndexRoute
  '/reliability': typeof AuthenticatedReliabilityIndexRoute
  '/requests': typeof AuthenticatedRequestsIndexRoute
  '/service-orders': typeof AuthenticatedServiceOrdersIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/access-code': typeof AccessCodeRoute
  '/magic-link': typeof MagicLinkRoute
  '/sign-in': typeof SignInRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsRouteRouteWithChildren
  '/_authenticated/requests': typeof AuthenticatedRequestsRouteRouteWithChildren
  '/_authenticated/service-orders': typeof AuthenticatedServiceOrdersRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/service-order-access/$token': typeof ServiceOrderAccessTokenRoute
  '/v/$token': typeof VTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/_authenticated/certificates/$id': typeof AuthenticatedCertificatesIdRoute
  '/_authenticated/requests/$id': typeof AuthenticatedRequestsIdRoute
  '/_authenticated/requests/new': typeof AuthenticatedRequestsNewRoute
  '/_authenticated/service-orders/$id': typeof AuthenticatedServiceOrdersIdRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/assets/': typeof AuthenticatedAssetsIndexRoute
  '/_authenticated/calendar/': typeof AuthenticatedCalendarIndexRoute
  '/_authenticated/certificates/': typeof AuthenticatedCertificatesIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/out-of-tolerance/': typeof AuthenticatedOutOfToleranceIndexRoute
  '/_authenticated/reliability/': typeof AuthenticatedReliabilityIndexRoute
  '/_authenticated/requests/': typeof AuthenticatedRequestsIndexRoute
  '/_authenticated/service-orders/': typeof AuthenticatedServiceOrdersIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/access-code'
    | '/magic-link'
    | '/sign-in'
    | '/assets'
    | '/requests'
    | '/service-orders'
    | '/settings'
    | '/service-order-access/$token'
    | '/v/$token'
    | '/assets/$id'
    | '/certificates/$id'
    | '/requests/$id'
    | '/requests/new'
    | '/service-orders/$id'
    | '/settings/appearance'
    | '/settings/notifications'
    | '/settings/profile'
    | '/assets/'
    | '/calendar/'
    | '/certificates/'
    | '/notifications/'
    | '/out-of-tolerance/'
    | '/reliability/'
    | '/requests/'
    | '/service-orders/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invite'
    | '/access-code'
    | '/magic-link'
    | '/sign-in'
    | '/service-order-access/$token'
    | '/v/$token'
    | '/'
    | '/assets/$id'
    | '/certificates/$id'
    | '/requests/$id'
    | '/requests/new'
    | '/service-orders/$id'
    | '/settings/appearance'
    | '/settings/notifications'
    | '/settings/profile'
    | '/assets'
    | '/calendar'
    | '/certificates'
    | '/notifications'
    | '/out-of-tolerance'
    | '/reliability'
    | '/requests'
    | '/service-orders'
    | '/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/accept-invite'
    | '/access-code'
    | '/magic-link'
    | '/sign-in'
    | '/_authenticated/assets'
    | '/_authenticated/requests'
    | '/_authenticated/service-orders'
    | '/_authenticated/settings'
    | '/service-order-access/$token'
    | '/v/$token'
    | '/_authenticated/'
    | '/_authenticated/assets/$id'
    | '/_authenticated/certificates/$id'
    | '/_authenticated/requests/$id'
    | '/_authenticated/requests/new'
    | '/_authenticated/service-orders/$id'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/profile'
    | '/_authenticated/assets/'
    | '/_authenticated/calendar/'
    | '/_authenticated/certificates/'
    | '/_authenticated/notifications/'
    | '/_authenticated/out-of-tolerance/'
    | '/_authenticated/reliability/'
    | '/_authenticated/requests/'
    | '/_authenticated/service-orders/'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  AccessCodeRoute: typeof AccessCodeRoute
  MagicLinkRoute: typeof MagicLinkRoute
  SignInRoute: typeof SignInRoute
  ServiceOrderAccessTokenRoute: typeof ServiceOrderAccessTokenRoute
  VTokenRoute: typeof VTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magic-link': {
      id: '/magic-link'
      path: '/magic-link'
      fullPath: '/magic-link'
      preLoaderRoute: typeof MagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-code': {
      id: '/access-code'
      path: '/access-code'
      fullPath: '/access-code'
      preLoaderRoute: typeof AccessCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/v/$token': {
      id: '/v/$token'
      path: '/v/$token'
      fullPath: '/v/$token'
      preLoaderRoute: typeof VTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-order-access/$token': {
      id: '/service-order-access/$token'
      path: '/service-order-access/$token'
      fullPath: '/service-order-access/$token'
      preLoaderRoute: typeof ServiceOrderAccessTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/service-orders': {
      id: '/_authenticated/service-orders'
      path: '/service-orders'
      fullPath: '/service-orders'
      preLoaderRoute: typeof AuthenticatedServiceOrdersRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/service-orders/': {
      id: '/_authenticated/service-orders/'
      path: '/'
      fullPath: '/service-orders/'
      preLoaderRoute: typeof AuthenticatedServiceOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedServiceOrdersRouteRoute
    }
    '/_authenticated/requests/': {
      id: '/_authenticated/requests/'
      path: '/'
      fullPath: '/requests/'
      preLoaderRoute: typeof AuthenticatedRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRequestsRouteRoute
    }
    '/_authenticated/reliability/': {
      id: '/_authenticated/reliability/'
      path: '/reliability'
      fullPath: '/reliability/'
      preLoaderRoute: typeof AuthenticatedReliabilityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/out-of-tolerance/': {
      id: '/_authenticated/out-of-tolerance/'
      path: '/out-of-tolerance'
      fullPath: '/out-of-tolerance/'
      preLoaderRoute: typeof AuthenticatedOutOfToleranceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificates/': {
      id: '/_authenticated/certificates/'
      path: '/certificates'
      fullPath: '/certificates/'
      preLoaderRoute: typeof AuthenticatedCertificatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar/': {
      id: '/_authenticated/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof AuthenticatedCalendarIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets/': {
      id: '/_authenticated/assets/'
      path: '/'
      fullPath: '/assets/'
      preLoaderRoute: typeof AuthenticatedAssetsIndexRouteImport
      parentRoute: typeof AuthenticatedAssetsRouteRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/service-orders/$id': {
      id: '/_authenticated/service-orders/$id'
      path: '/$id'
      fullPath: '/service-orders/$id'
      preLoaderRoute: typeof AuthenticatedServiceOrdersIdRouteImport
      parentRoute: typeof AuthenticatedServiceOrdersRouteRoute
    }
    '/_authenticated/requests/new': {
      id: '/_authenticated/requests/new'
      path: '/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof AuthenticatedRequestsNewRouteImport
      parentRoute: typeof AuthenticatedRequestsRouteRoute
    }
    '/_authenticated/requests/$id': {
      id: '/_authenticated/requests/$id'
      path: '/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof AuthenticatedRequestsIdRouteImport
      parentRoute: typeof AuthenticatedRequestsRouteRoute
    }
    '/_authenticated/certificates/$id': {
      id: '/_authenticated/certificates/$id'
      path: '/certificates/$id'
      fullPath: '/certificates/$id'
      preLoaderRoute: typeof AuthenticatedCertificatesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets/$id': {
      id: '/_authenticated/assets/$id'
      path: '/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AuthenticatedAssetsIdRouteImport
      parentRoute: typeof AuthenticatedAssetsRouteRoute
    }
  }
}

interface AuthenticatedAssetsRouteRouteChildren {
  AuthenticatedAssetsIdRoute: typeof AuthenticatedAssetsIdRoute
  AuthenticatedAssetsIndexRoute: typeof AuthenticatedAssetsIndexRoute
}

const AuthenticatedAssetsRouteRouteChildren: AuthenticatedAssetsRouteRouteChildren =
  {
    AuthenticatedAssetsIdRoute: AuthenticatedAssetsIdRoute,
    AuthenticatedAssetsIndexRoute: AuthenticatedAssetsIndexRoute,
  }

const AuthenticatedAssetsRouteRouteWithChildren =
  AuthenticatedAssetsRouteRoute._addFileChildren(
    AuthenticatedAssetsRouteRouteChildren,
  )

interface AuthenticatedRequestsRouteRouteChildren {
  AuthenticatedRequestsIdRoute: typeof AuthenticatedRequestsIdRoute
  AuthenticatedRequestsNewRoute: typeof AuthenticatedRequestsNewRoute
  AuthenticatedRequestsIndexRoute: typeof AuthenticatedRequestsIndexRoute
}

const AuthenticatedRequestsRouteRouteChildren: AuthenticatedRequestsRouteRouteChildren =
  {
    AuthenticatedRequestsIdRoute: AuthenticatedRequestsIdRoute,
    AuthenticatedRequestsNewRoute: AuthenticatedRequestsNewRoute,
    AuthenticatedRequestsIndexRoute: AuthenticatedRequestsIndexRoute,
  }

const AuthenticatedRequestsRouteRouteWithChildren =
  AuthenticatedRequestsRouteRoute._addFileChildren(
    AuthenticatedRequestsRouteRouteChildren,
  )

interface AuthenticatedServiceOrdersRouteRouteChildren {
  AuthenticatedServiceOrdersIdRoute: typeof AuthenticatedServiceOrdersIdRoute
  AuthenticatedServiceOrdersIndexRoute: typeof AuthenticatedServiceOrdersIndexRoute
}

const AuthenticatedServiceOrdersRouteRouteChildren: AuthenticatedServiceOrdersRouteRouteChildren =
  {
    AuthenticatedServiceOrdersIdRoute: AuthenticatedServiceOrdersIdRoute,
    AuthenticatedServiceOrdersIndexRoute: AuthenticatedServiceOrdersIndexRoute,
  }

const AuthenticatedServiceOrdersRouteRouteWithChildren =
  AuthenticatedServiceOrdersRouteRoute._addFileChildren(
    AuthenticatedServiceOrdersRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssetsRouteRoute: typeof AuthenticatedAssetsRouteRouteWithChildren
  AuthenticatedRequestsRouteRoute: typeof AuthenticatedRequestsRouteRouteWithChildren
  AuthenticatedServiceOrdersRouteRoute: typeof AuthenticatedServiceOrdersRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCertificatesIdRoute: typeof AuthenticatedCertificatesIdRoute
  AuthenticatedCalendarIndexRoute: typeof AuthenticatedCalendarIndexRoute
  AuthenticatedCertificatesIndexRoute: typeof AuthenticatedCertificatesIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedOutOfToleranceIndexRoute: typeof AuthenticatedOutOfToleranceIndexRoute
  AuthenticatedReliabilityIndexRoute: typeof AuthenticatedReliabilityIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssetsRouteRoute: AuthenticatedAssetsRouteRouteWithChildren,
  AuthenticatedRequestsRouteRoute: AuthenticatedRequestsRouteRouteWithChildren,
  AuthenticatedServiceOrdersRouteRoute:
    AuthenticatedServiceOrdersRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCertificatesIdRoute: AuthenticatedCertificatesIdRoute,
  AuthenticatedCalendarIndexRoute: AuthenticatedCalendarIndexRoute,
  AuthenticatedCertificatesIndexRoute: AuthenticatedCertificatesIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedOutOfToleranceIndexRoute: AuthenticatedOutOfToleranceIndexRoute,
  AuthenticatedReliabilityIndexRoute: AuthenticatedReliabilityIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  AccessCodeRoute: AccessCodeRoute,
  MagicLinkRoute: MagicLinkRoute,
  SignInRoute: SignInRoute,
  ServiceOrderAccessTokenRoute: ServiceOrderAccessTokenRoute,
  VTokenRoute: VTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
