export const migration0002ServiceOrderIntake = {
  id: 2,
  name: "service_order_intake",
  sql: `
CREATE TABLE IF NOT EXISTS service_orders (
  id TEXT PRIMARY KEY,
  remote_id INTEGER,
  service_order_number TEXT NOT NULL,
  organization_id TEXT NOT NULL,
  unit_id INTEGER NOT NULL,
  customer_id TEXT NOT NULL,
  asset_id TEXT NOT NULL,
  client_contact_id INTEGER,
  client_contact_snapshot_json TEXT,
  intake_type TEXT NOT NULL,
  source_service_order_id INTEGER,
  status TEXT NOT NULL,
  priority TEXT NOT NULL,
  responsible_technician_id TEXT,
  claimed_defect TEXT NOT NULL,
  intake_condition TEXT NOT NULL,
  accessories TEXT,
  old_seal_number TEXT,
  new_seal_number TEXT,
  repaired_seal_number TEXT,
  inmetro_repair_seal_number TEXT,
  invoice_remittance_number TEXT,
  invoice_remittance_key TEXT,
  invoice_remittance_issued_at TEXT,
  carrier_name TEXT,
  carrier_document TEXT,
  third_party_name TEXT,
  third_party_document TEXT,
  third_party_phone TEXT,
  delivery_method TEXT NOT NULL,
  internal_notes TEXT,
  client_visible_notes TEXT,
  evaluation_fee_cents INTEGER NOT NULL DEFAULT 0,
  warranty_until TEXT,
  warranty_terms TEXT,
  opened_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  sync_state TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS service_order_asset_snapshots (
  service_order_id TEXT PRIMARY KEY,
  asset_id INTEGER,
  asset_name TEXT NOT NULL,
  asset_type TEXT,
  manufacturer TEXT,
  model TEXT,
  serial_number TEXT,
  patrimony_number TEXT,
  capacity TEXT,
  resolution TEXT,
  inventory_code TEXT,
  client_asset_code TEXT,
  observed_identification TEXT,
  photos_json TEXT NOT NULL,
  specifications_json TEXT NOT NULL
);
`,
} as const;
