/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AcceptInvitationIdRouteImport } from './routes/accept-invitation/$id'
import { Route as DashboardSettingsRouteRouteImport } from './routes/dashboard/settings/route'
import { Route as DashboardClientsRouteRouteImport } from './routes/dashboard/clients/route'
import { Route as DashboardClientsIndexRouteImport } from './routes/dashboard/clients/index'
import { Route as DashboardSettingsSecurityRouteImport } from './routes/dashboard/settings/security'
import { Route as DashboardSettingsProfileRouteImport } from './routes/dashboard/settings/profile'
import { Route as DashboardSettingsOrganizationRouteImport } from './routes/dashboard/settings/organization'
import { Route as DashboardSettingsNotificationsRouteImport } from './routes/dashboard/settings/notifications'
import { Route as DashboardSettingsDangerRouteImport } from './routes/dashboard/settings/danger'
import { Route as DashboardSettingsBillingRouteImport } from './routes/dashboard/settings/billing'
import { Route as DashboardSettingsAuthenticationRouteImport } from './routes/dashboard/settings/authentication'
import { Route as DashboardSettingsAppearanceRouteImport } from './routes/dashboard/settings/appearance'
import { Route as DashboardClientsNewRouteImport } from './routes/dashboard/clients/new'
import { Route as DashboardClientsIdRouteRouteImport } from './routes/dashboard/clients/$id/route'
import { Route as DashboardClientsIdIndexRouteImport } from './routes/dashboard/clients/$id/index'
import { Route as DashboardClientsIdUsersRouteImport } from './routes/dashboard/clients/$id/users'
import { Route as DashboardClientsIdInfoRouteImport } from './routes/dashboard/clients/$id/info'
import { Route as DashboardClientsIdEquipmentRouteImport } from './routes/dashboard/clients/$id/equipment'
import { Route as DashboardClientsIdComplianceRouteImport } from './routes/dashboard/clients/$id/compliance'
import { Route as DashboardClientsIdCalibrationsRouteImport } from './routes/dashboard/clients/$id/calibrations'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AcceptInvitationIdRoute = AcceptInvitationIdRouteImport.update({
  id: '/accept-invitation/$id',
  path: '/accept-invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRouteRoute = DashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardClientsRouteRoute = DashboardClientsRouteRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardClientsIndexRoute = DashboardClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardClientsRouteRoute,
} as any)
const DashboardSettingsSecurityRoute =
  DashboardSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsProfileRoute =
  DashboardSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsOrganizationRoute =
  DashboardSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsNotificationsRoute =
  DashboardSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsDangerRoute = DashboardSettingsDangerRouteImport.update({
  id: '/danger',
  path: '/danger',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)
const DashboardSettingsBillingRoute =
  DashboardSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsAuthenticationRoute =
  DashboardSettingsAuthenticationRouteImport.update({
    id: '/authentication',
    path: '/authentication',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsAppearanceRoute =
  DashboardSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardClientsNewRoute = DashboardClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardClientsRouteRoute,
} as any)
const DashboardClientsIdRouteRoute = DashboardClientsIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardClientsRouteRoute,
} as any)
const DashboardClientsIdIndexRoute = DashboardClientsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardClientsIdRouteRoute,
} as any)
const DashboardClientsIdUsersRoute = DashboardClientsIdUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardClientsIdRouteRoute,
} as any)
const DashboardClientsIdInfoRoute = DashboardClientsIdInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => DashboardClientsIdRouteRoute,
} as any)
const DashboardClientsIdEquipmentRoute =
  DashboardClientsIdEquipmentRouteImport.update({
    id: '/equipment',
    path: '/equipment',
    getParentRoute: () => DashboardClientsIdRouteRoute,
  } as any)
const DashboardClientsIdComplianceRoute =
  DashboardClientsIdComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => DashboardClientsIdRouteRoute,
  } as any)
const DashboardClientsIdCalibrationsRoute =
  DashboardClientsIdCalibrationsRouteImport.update({
    id: '/calibrations',
    path: '/calibrations',
    getParentRoute: () => DashboardClientsIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/clients': typeof DashboardClientsRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/dashboard/clients/$id': typeof DashboardClientsIdRouteRouteWithChildren
  '/dashboard/clients/new': typeof DashboardClientsNewRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/dashboard/settings/authentication': typeof DashboardSettingsAuthenticationRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/danger': typeof DashboardSettingsDangerRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/organization': typeof DashboardSettingsOrganizationRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
  '/dashboard/clients/$id/calibrations': typeof DashboardClientsIdCalibrationsRoute
  '/dashboard/clients/$id/compliance': typeof DashboardClientsIdComplianceRoute
  '/dashboard/clients/$id/equipment': typeof DashboardClientsIdEquipmentRoute
  '/dashboard/clients/$id/info': typeof DashboardClientsIdInfoRoute
  '/dashboard/clients/$id/users': typeof DashboardClientsIdUsersRoute
  '/dashboard/clients/$id/': typeof DashboardClientsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/dashboard/clients/new': typeof DashboardClientsNewRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/dashboard/settings/authentication': typeof DashboardSettingsAuthenticationRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/danger': typeof DashboardSettingsDangerRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/organization': typeof DashboardSettingsOrganizationRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/clients': typeof DashboardClientsIndexRoute
  '/dashboard/clients/$id/calibrations': typeof DashboardClientsIdCalibrationsRoute
  '/dashboard/clients/$id/compliance': typeof DashboardClientsIdComplianceRoute
  '/dashboard/clients/$id/equipment': typeof DashboardClientsIdEquipmentRoute
  '/dashboard/clients/$id/info': typeof DashboardClientsIdInfoRoute
  '/dashboard/clients/$id/users': typeof DashboardClientsIdUsersRoute
  '/dashboard/clients/$id': typeof DashboardClientsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/clients': typeof DashboardClientsRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/dashboard/clients/$id': typeof DashboardClientsIdRouteRouteWithChildren
  '/dashboard/clients/new': typeof DashboardClientsNewRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/dashboard/settings/authentication': typeof DashboardSettingsAuthenticationRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/danger': typeof DashboardSettingsDangerRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/organization': typeof DashboardSettingsOrganizationRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
  '/dashboard/clients/$id/calibrations': typeof DashboardClientsIdCalibrationsRoute
  '/dashboard/clients/$id/compliance': typeof DashboardClientsIdComplianceRoute
  '/dashboard/clients/$id/equipment': typeof DashboardClientsIdEquipmentRoute
  '/dashboard/clients/$id/info': typeof DashboardClientsIdInfoRoute
  '/dashboard/clients/$id/users': typeof DashboardClientsIdUsersRoute
  '/dashboard/clients/$id/': typeof DashboardClientsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/clients'
    | '/dashboard/settings'
    | '/accept-invitation/$id'
    | '/dashboard/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/clients/$id'
    | '/dashboard/clients/new'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/authentication'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/danger'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/organization'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/security'
    | '/dashboard/clients/'
    | '/dashboard/clients/$id/calibrations'
    | '/dashboard/clients/$id/compliance'
    | '/dashboard/clients/$id/equipment'
    | '/dashboard/clients/$id/info'
    | '/dashboard/clients/$id/users'
    | '/dashboard/clients/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/settings'
    | '/accept-invitation/$id'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/clients/new'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/authentication'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/danger'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/organization'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/security'
    | '/dashboard/clients'
    | '/dashboard/clients/$id/calibrations'
    | '/dashboard/clients/$id/compliance'
    | '/dashboard/clients/$id/equipment'
    | '/dashboard/clients/$id/info'
    | '/dashboard/clients/$id/users'
    | '/dashboard/clients/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/clients'
    | '/dashboard/settings'
    | '/accept-invitation/$id'
    | '/dashboard/'
    | '/sign-in/'
    | '/sign-up/'
    | '/dashboard/clients/$id'
    | '/dashboard/clients/new'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/authentication'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/danger'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/organization'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/security'
    | '/dashboard/clients/'
    | '/dashboard/clients/$id/calibrations'
    | '/dashboard/clients/$id/compliance'
    | '/dashboard/clients/$id/equipment'
    | '/dashboard/clients/$id/info'
    | '/dashboard/clients/$id/users'
    | '/dashboard/clients/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AcceptInvitationIdRoute: typeof AcceptInvitationIdRoute
  SignInIndexRoute: typeof SignInIndexRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/accept-invitation/$id': {
      id: '/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof AcceptInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/clients': {
      id: '/dashboard/clients'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardClientsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/clients/': {
      id: '/dashboard/clients/'
      path: '/'
      fullPath: '/dashboard/clients/'
      preLoaderRoute: typeof DashboardClientsIndexRouteImport
      parentRoute: typeof DashboardClientsRouteRoute
    }
    '/dashboard/settings/security': {
      id: '/dashboard/settings/security'
      path: '/security'
      fullPath: '/dashboard/settings/security'
      preLoaderRoute: typeof DashboardSettingsSecurityRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/profile': {
      id: '/dashboard/settings/profile'
      path: '/profile'
      fullPath: '/dashboard/settings/profile'
      preLoaderRoute: typeof DashboardSettingsProfileRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/organization': {
      id: '/dashboard/settings/organization'
      path: '/organization'
      fullPath: '/dashboard/settings/organization'
      preLoaderRoute: typeof DashboardSettingsOrganizationRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/notifications': {
      id: '/dashboard/settings/notifications'
      path: '/notifications'
      fullPath: '/dashboard/settings/notifications'
      preLoaderRoute: typeof DashboardSettingsNotificationsRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/danger': {
      id: '/dashboard/settings/danger'
      path: '/danger'
      fullPath: '/dashboard/settings/danger'
      preLoaderRoute: typeof DashboardSettingsDangerRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/billing': {
      id: '/dashboard/settings/billing'
      path: '/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof DashboardSettingsBillingRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/authentication': {
      id: '/dashboard/settings/authentication'
      path: '/authentication'
      fullPath: '/dashboard/settings/authentication'
      preLoaderRoute: typeof DashboardSettingsAuthenticationRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/appearance': {
      id: '/dashboard/settings/appearance'
      path: '/appearance'
      fullPath: '/dashboard/settings/appearance'
      preLoaderRoute: typeof DashboardSettingsAppearanceRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/clients/new': {
      id: '/dashboard/clients/new'
      path: '/new'
      fullPath: '/dashboard/clients/new'
      preLoaderRoute: typeof DashboardClientsNewRouteImport
      parentRoute: typeof DashboardClientsRouteRoute
    }
    '/dashboard/clients/$id': {
      id: '/dashboard/clients/$id'
      path: '/$id'
      fullPath: '/dashboard/clients/$id'
      preLoaderRoute: typeof DashboardClientsIdRouteRouteImport
      parentRoute: typeof DashboardClientsRouteRoute
    }
    '/dashboard/clients/$id/': {
      id: '/dashboard/clients/$id/'
      path: '/'
      fullPath: '/dashboard/clients/$id/'
      preLoaderRoute: typeof DashboardClientsIdIndexRouteImport
      parentRoute: typeof DashboardClientsIdRouteRoute
    }
    '/dashboard/clients/$id/users': {
      id: '/dashboard/clients/$id/users'
      path: '/users'
      fullPath: '/dashboard/clients/$id/users'
      preLoaderRoute: typeof DashboardClientsIdUsersRouteImport
      parentRoute: typeof DashboardClientsIdRouteRoute
    }
    '/dashboard/clients/$id/info': {
      id: '/dashboard/clients/$id/info'
      path: '/info'
      fullPath: '/dashboard/clients/$id/info'
      preLoaderRoute: typeof DashboardClientsIdInfoRouteImport
      parentRoute: typeof DashboardClientsIdRouteRoute
    }
    '/dashboard/clients/$id/equipment': {
      id: '/dashboard/clients/$id/equipment'
      path: '/equipment'
      fullPath: '/dashboard/clients/$id/equipment'
      preLoaderRoute: typeof DashboardClientsIdEquipmentRouteImport
      parentRoute: typeof DashboardClientsIdRouteRoute
    }
    '/dashboard/clients/$id/compliance': {
      id: '/dashboard/clients/$id/compliance'
      path: '/compliance'
      fullPath: '/dashboard/clients/$id/compliance'
      preLoaderRoute: typeof DashboardClientsIdComplianceRouteImport
      parentRoute: typeof DashboardClientsIdRouteRoute
    }
    '/dashboard/clients/$id/calibrations': {
      id: '/dashboard/clients/$id/calibrations'
      path: '/calibrations'
      fullPath: '/dashboard/clients/$id/calibrations'
      preLoaderRoute: typeof DashboardClientsIdCalibrationsRouteImport
      parentRoute: typeof DashboardClientsIdRouteRoute
    }
  }
}

interface DashboardClientsIdRouteRouteChildren {
  DashboardClientsIdCalibrationsRoute: typeof DashboardClientsIdCalibrationsRoute
  DashboardClientsIdComplianceRoute: typeof DashboardClientsIdComplianceRoute
  DashboardClientsIdEquipmentRoute: typeof DashboardClientsIdEquipmentRoute
  DashboardClientsIdInfoRoute: typeof DashboardClientsIdInfoRoute
  DashboardClientsIdUsersRoute: typeof DashboardClientsIdUsersRoute
  DashboardClientsIdIndexRoute: typeof DashboardClientsIdIndexRoute
}

const DashboardClientsIdRouteRouteChildren: DashboardClientsIdRouteRouteChildren =
  {
    DashboardClientsIdCalibrationsRoute: DashboardClientsIdCalibrationsRoute,
    DashboardClientsIdComplianceRoute: DashboardClientsIdComplianceRoute,
    DashboardClientsIdEquipmentRoute: DashboardClientsIdEquipmentRoute,
    DashboardClientsIdInfoRoute: DashboardClientsIdInfoRoute,
    DashboardClientsIdUsersRoute: DashboardClientsIdUsersRoute,
    DashboardClientsIdIndexRoute: DashboardClientsIdIndexRoute,
  }

const DashboardClientsIdRouteRouteWithChildren =
  DashboardClientsIdRouteRoute._addFileChildren(
    DashboardClientsIdRouteRouteChildren,
  )

interface DashboardClientsRouteRouteChildren {
  DashboardClientsIdRouteRoute: typeof DashboardClientsIdRouteRouteWithChildren
  DashboardClientsNewRoute: typeof DashboardClientsNewRoute
  DashboardClientsIndexRoute: typeof DashboardClientsIndexRoute
}

const DashboardClientsRouteRouteChildren: DashboardClientsRouteRouteChildren = {
  DashboardClientsIdRouteRoute: DashboardClientsIdRouteRouteWithChildren,
  DashboardClientsNewRoute: DashboardClientsNewRoute,
  DashboardClientsIndexRoute: DashboardClientsIndexRoute,
}

const DashboardClientsRouteRouteWithChildren =
  DashboardClientsRouteRoute._addFileChildren(
    DashboardClientsRouteRouteChildren,
  )

interface DashboardSettingsRouteRouteChildren {
  DashboardSettingsAppearanceRoute: typeof DashboardSettingsAppearanceRoute
  DashboardSettingsAuthenticationRoute: typeof DashboardSettingsAuthenticationRoute
  DashboardSettingsBillingRoute: typeof DashboardSettingsBillingRoute
  DashboardSettingsDangerRoute: typeof DashboardSettingsDangerRoute
  DashboardSettingsNotificationsRoute: typeof DashboardSettingsNotificationsRoute
  DashboardSettingsOrganizationRoute: typeof DashboardSettingsOrganizationRoute
  DashboardSettingsProfileRoute: typeof DashboardSettingsProfileRoute
  DashboardSettingsSecurityRoute: typeof DashboardSettingsSecurityRoute
}

const DashboardSettingsRouteRouteChildren: DashboardSettingsRouteRouteChildren =
  {
    DashboardSettingsAppearanceRoute: DashboardSettingsAppearanceRoute,
    DashboardSettingsAuthenticationRoute: DashboardSettingsAuthenticationRoute,
    DashboardSettingsBillingRoute: DashboardSettingsBillingRoute,
    DashboardSettingsDangerRoute: DashboardSettingsDangerRoute,
    DashboardSettingsNotificationsRoute: DashboardSettingsNotificationsRoute,
    DashboardSettingsOrganizationRoute: DashboardSettingsOrganizationRoute,
    DashboardSettingsProfileRoute: DashboardSettingsProfileRoute,
    DashboardSettingsSecurityRoute: DashboardSettingsSecurityRoute,
  }

const DashboardSettingsRouteRouteWithChildren =
  DashboardSettingsRouteRoute._addFileChildren(
    DashboardSettingsRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardClientsRouteRoute: typeof DashboardClientsRouteRouteWithChildren
  DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardClientsRouteRoute: DashboardClientsRouteRouteWithChildren,
  DashboardSettingsRouteRoute: DashboardSettingsRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AcceptInvitationIdRoute: AcceptInvitationIdRoute,
  SignInIndexRoute: SignInIndexRoute,
  SignUpIndexRoute: SignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
