/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AcceptInvitationIdRouteImport } from './routes/accept-invitation/$id'
import { Route as DashboardStandardsRouteRouteImport } from './routes/dashboard/standards/route'
import { Route as DashboardSettingsRouteRouteImport } from './routes/dashboard/settings/route'
import { Route as DashboardServicesRouteRouteImport } from './routes/dashboard/services/route'
import { Route as DashboardMethodsRouteRouteImport } from './routes/dashboard/methods/route'
import { Route as DashboardJobsRouteRouteImport } from './routes/dashboard/jobs/route'
import { Route as DashboardClientsRouteRouteImport } from './routes/dashboard/clients/route'
import { Route as DashboardAssetsRouteRouteImport } from './routes/dashboard/assets/route'
import { Route as DashboardStandardsIndexRouteImport } from './routes/dashboard/standards/index'
import { Route as DashboardServicesIndexRouteImport } from './routes/dashboard/services/index'
import { Route as DashboardMethodsIndexRouteImport } from './routes/dashboard/methods/index'
import { Route as DashboardJobsIndexRouteImport } from './routes/dashboard/jobs/index'
import { Route as DashboardClientsIndexRouteImport } from './routes/dashboard/clients/index'
import { Route as DashboardAssetsIndexRouteImport } from './routes/dashboard/assets/index'
import { Route as DashboardStandardsNewRouteImport } from './routes/dashboard/standards/new'
import { Route as DashboardSettingsSecurityRouteImport } from './routes/dashboard/settings/security'
import { Route as DashboardSettingsProfileRouteImport } from './routes/dashboard/settings/profile'
import { Route as DashboardSettingsOrganizationRouteImport } from './routes/dashboard/settings/organization'
import { Route as DashboardSettingsNotificationsRouteImport } from './routes/dashboard/settings/notifications'
import { Route as DashboardSettingsDangerRouteImport } from './routes/dashboard/settings/danger'
import { Route as DashboardSettingsBillingRouteImport } from './routes/dashboard/settings/billing'
import { Route as DashboardSettingsAuthenticationRouteImport } from './routes/dashboard/settings/authentication'
import { Route as DashboardSettingsAppearanceRouteImport } from './routes/dashboard/settings/appearance'
import { Route as DashboardServicesNewRouteImport } from './routes/dashboard/services/new'
import { Route as DashboardMethodsNewRouteImport } from './routes/dashboard/methods/new'
import { Route as DashboardJobsNewRouteImport } from './routes/dashboard/jobs/new'
import { Route as DashboardClientsNewRouteImport } from './routes/dashboard/clients/new'
import { Route as DashboardAssetsNewRouteImport } from './routes/dashboard/assets/new'
import { Route as DashboardClientsIdRouteRouteImport } from './routes/dashboard/clients/$id/route'
import { Route as DashboardAssetsIdRouteRouteImport } from './routes/dashboard/assets/$id/route'
import { Route as DashboardMethodsIdIndexRouteImport } from './routes/dashboard/methods/$id/index'
import { Route as DashboardJobsIdIndexRouteImport } from './routes/dashboard/jobs/$id/index'
import { Route as DashboardClientsIdIndexRouteImport } from './routes/dashboard/clients/$id/index'
import { Route as DashboardAssetsIdIndexRouteImport } from './routes/dashboard/assets/$id/index'
import { Route as DashboardStandardsIdEditRouteImport } from './routes/dashboard/standards/$id/edit'
import { Route as DashboardServicesIdEditRouteImport } from './routes/dashboard/services/$id/edit'
import { Route as DashboardMethodsIdEditRouteImport } from './routes/dashboard/methods/$id/edit'
import { Route as DashboardJobsIdExecuteRouteImport } from './routes/dashboard/jobs/$id/execute'
import { Route as DashboardClientsIdUsersRouteImport } from './routes/dashboard/clients/$id/users'
import { Route as DashboardClientsIdInfoRouteImport } from './routes/dashboard/clients/$id/info'
import { Route as DashboardClientsIdComplianceRouteImport } from './routes/dashboard/clients/$id/compliance'
import { Route as DashboardClientsIdCalibrationsRouteImport } from './routes/dashboard/clients/$id/calibrations'
import { Route as DashboardClientsIdAssetsRouteImport } from './routes/dashboard/clients/$id/assets'
import { Route as DashboardAssetsIdEditRouteImport } from './routes/dashboard/assets/$id/edit'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AcceptInvitationIdRoute = AcceptInvitationIdRouteImport.update({
  id: '/accept-invitation/$id',
  path: '/accept-invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStandardsRouteRoute = DashboardStandardsRouteRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRouteRoute = DashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardServicesRouteRoute = DashboardServicesRouteRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMethodsRouteRoute = DashboardMethodsRouteRouteImport.update({
  id: '/methods',
  path: '/methods',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardJobsRouteRoute = DashboardJobsRouteRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardClientsRouteRoute = DashboardClientsRouteRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAssetsRouteRoute = DashboardAssetsRouteRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardStandardsIndexRoute = DashboardStandardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardStandardsRouteRoute,
} as any)
const DashboardServicesIndexRoute = DashboardServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardServicesRouteRoute,
} as any)
const DashboardMethodsIndexRoute = DashboardMethodsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardMethodsRouteRoute,
} as any)
const DashboardJobsIndexRoute = DashboardJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardJobsRouteRoute,
} as any)
const DashboardClientsIndexRoute = DashboardClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardClientsRouteRoute,
} as any)
const DashboardAssetsIndexRoute = DashboardAssetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAssetsRouteRoute,
} as any)
const DashboardStandardsNewRoute = DashboardStandardsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardStandardsRouteRoute,
} as any)
const DashboardSettingsSecurityRoute =
  DashboardSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsProfileRoute =
  DashboardSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsOrganizationRoute =
  DashboardSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsNotificationsRoute =
  DashboardSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsDangerRoute = DashboardSettingsDangerRouteImport.update({
  id: '/danger',
  path: '/danger',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)
const DashboardSettingsBillingRoute =
  DashboardSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsAuthenticationRoute =
  DashboardSettingsAuthenticationRouteImport.update({
    id: '/authentication',
    path: '/authentication',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsAppearanceRoute =
  DashboardSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardServicesNewRoute = DashboardServicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardServicesRouteRoute,
} as any)
const DashboardMethodsNewRoute = DashboardMethodsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardMethodsRouteRoute,
} as any)
const DashboardJobsNewRoute = DashboardJobsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardJobsRouteRoute,
} as any)
const DashboardClientsNewRoute = DashboardClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardClientsRouteRoute,
} as any)
const DashboardAssetsNewRoute = DashboardAssetsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardAssetsRouteRoute,
} as any)
const DashboardClientsIdRouteRoute = DashboardClientsIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardClientsRouteRoute,
} as any)
const DashboardAssetsIdRouteRoute = DashboardAssetsIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardAssetsRouteRoute,
} as any)
const DashboardMethodsIdIndexRoute = DashboardMethodsIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => DashboardMethodsRouteRoute,
} as any)
const DashboardJobsIdIndexRoute = DashboardJobsIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => DashboardJobsRouteRoute,
} as any)
const DashboardClientsIdIndexRoute = DashboardClientsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardClientsIdRouteRoute,
} as any)
const DashboardAssetsIdIndexRoute = DashboardAssetsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAssetsIdRouteRoute,
} as any)
const DashboardStandardsIdEditRoute =
  DashboardStandardsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => DashboardStandardsRouteRoute,
  } as any)
const DashboardServicesIdEditRoute = DashboardServicesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => DashboardServicesRouteRoute,
} as any)
const DashboardMethodsIdEditRoute = DashboardMethodsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => DashboardMethodsRouteRoute,
} as any)
const DashboardJobsIdExecuteRoute = DashboardJobsIdExecuteRouteImport.update({
  id: '/$id/execute',
  path: '/$id/execute',
  getParentRoute: () => DashboardJobsRouteRoute,
} as any)
const DashboardClientsIdUsersRoute = DashboardClientsIdUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardClientsIdRouteRoute,
} as any)
const DashboardClientsIdInfoRoute = DashboardClientsIdInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => DashboardClientsIdRouteRoute,
} as any)
const DashboardClientsIdComplianceRoute =
  DashboardClientsIdComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => DashboardClientsIdRouteRoute,
  } as any)
const DashboardClientsIdCalibrationsRoute =
  DashboardClientsIdCalibrationsRouteImport.update({
    id: '/calibrations',
    path: '/calibrations',
    getParentRoute: () => DashboardClientsIdRouteRoute,
  } as any)
const DashboardClientsIdAssetsRoute =
  DashboardClientsIdAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => DashboardClientsIdRouteRoute,
  } as any)
const DashboardAssetsIdEditRoute = DashboardAssetsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DashboardAssetsIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/assets': typeof DashboardAssetsRouteRouteWithChildren
  '/dashboard/clients': typeof DashboardClientsRouteRouteWithChildren
  '/dashboard/jobs': typeof DashboardJobsRouteRouteWithChildren
  '/dashboard/methods': typeof DashboardMethodsRouteRouteWithChildren
  '/dashboard/services': typeof DashboardServicesRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/dashboard/standards': typeof DashboardStandardsRouteRouteWithChildren
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/dashboard/assets/$id': typeof DashboardAssetsIdRouteRouteWithChildren
  '/dashboard/clients/$id': typeof DashboardClientsIdRouteRouteWithChildren
  '/dashboard/assets/new': typeof DashboardAssetsNewRoute
  '/dashboard/clients/new': typeof DashboardClientsNewRoute
  '/dashboard/jobs/new': typeof DashboardJobsNewRoute
  '/dashboard/methods/new': typeof DashboardMethodsNewRoute
  '/dashboard/services/new': typeof DashboardServicesNewRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/dashboard/settings/authentication': typeof DashboardSettingsAuthenticationRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/danger': typeof DashboardSettingsDangerRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/organization': typeof DashboardSettingsOrganizationRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/standards/new': typeof DashboardStandardsNewRoute
  '/dashboard/assets/': typeof DashboardAssetsIndexRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
  '/dashboard/jobs/': typeof DashboardJobsIndexRoute
  '/dashboard/methods/': typeof DashboardMethodsIndexRoute
  '/dashboard/services/': typeof DashboardServicesIndexRoute
  '/dashboard/standards/': typeof DashboardStandardsIndexRoute
  '/dashboard/assets/$id/edit': typeof DashboardAssetsIdEditRoute
  '/dashboard/clients/$id/assets': typeof DashboardClientsIdAssetsRoute
  '/dashboard/clients/$id/calibrations': typeof DashboardClientsIdCalibrationsRoute
  '/dashboard/clients/$id/compliance': typeof DashboardClientsIdComplianceRoute
  '/dashboard/clients/$id/info': typeof DashboardClientsIdInfoRoute
  '/dashboard/clients/$id/users': typeof DashboardClientsIdUsersRoute
  '/dashboard/jobs/$id/execute': typeof DashboardJobsIdExecuteRoute
  '/dashboard/methods/$id/edit': typeof DashboardMethodsIdEditRoute
  '/dashboard/services/$id/edit': typeof DashboardServicesIdEditRoute
  '/dashboard/standards/$id/edit': typeof DashboardStandardsIdEditRoute
  '/dashboard/assets/$id/': typeof DashboardAssetsIdIndexRoute
  '/dashboard/clients/$id/': typeof DashboardClientsIdIndexRoute
  '/dashboard/jobs/$id': typeof DashboardJobsIdIndexRoute
  '/dashboard/methods/$id': typeof DashboardMethodsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/dashboard/assets/new': typeof DashboardAssetsNewRoute
  '/dashboard/clients/new': typeof DashboardClientsNewRoute
  '/dashboard/jobs/new': typeof DashboardJobsNewRoute
  '/dashboard/methods/new': typeof DashboardMethodsNewRoute
  '/dashboard/services/new': typeof DashboardServicesNewRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/dashboard/settings/authentication': typeof DashboardSettingsAuthenticationRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/danger': typeof DashboardSettingsDangerRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/organization': typeof DashboardSettingsOrganizationRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/standards/new': typeof DashboardStandardsNewRoute
  '/dashboard/assets': typeof DashboardAssetsIndexRoute
  '/dashboard/clients': typeof DashboardClientsIndexRoute
  '/dashboard/jobs': typeof DashboardJobsIndexRoute
  '/dashboard/methods': typeof DashboardMethodsIndexRoute
  '/dashboard/services': typeof DashboardServicesIndexRoute
  '/dashboard/standards': typeof DashboardStandardsIndexRoute
  '/dashboard/assets/$id/edit': typeof DashboardAssetsIdEditRoute
  '/dashboard/clients/$id/assets': typeof DashboardClientsIdAssetsRoute
  '/dashboard/clients/$id/calibrations': typeof DashboardClientsIdCalibrationsRoute
  '/dashboard/clients/$id/compliance': typeof DashboardClientsIdComplianceRoute
  '/dashboard/clients/$id/info': typeof DashboardClientsIdInfoRoute
  '/dashboard/clients/$id/users': typeof DashboardClientsIdUsersRoute
  '/dashboard/jobs/$id/execute': typeof DashboardJobsIdExecuteRoute
  '/dashboard/methods/$id/edit': typeof DashboardMethodsIdEditRoute
  '/dashboard/services/$id/edit': typeof DashboardServicesIdEditRoute
  '/dashboard/standards/$id/edit': typeof DashboardStandardsIdEditRoute
  '/dashboard/assets/$id': typeof DashboardAssetsIdIndexRoute
  '/dashboard/clients/$id': typeof DashboardClientsIdIndexRoute
  '/dashboard/jobs/$id': typeof DashboardJobsIdIndexRoute
  '/dashboard/methods/$id': typeof DashboardMethodsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/assets': typeof DashboardAssetsRouteRouteWithChildren
  '/dashboard/clients': typeof DashboardClientsRouteRouteWithChildren
  '/dashboard/jobs': typeof DashboardJobsRouteRouteWithChildren
  '/dashboard/methods': typeof DashboardMethodsRouteRouteWithChildren
  '/dashboard/services': typeof DashboardServicesRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/dashboard/standards': typeof DashboardStandardsRouteRouteWithChildren
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/dashboard/assets/$id': typeof DashboardAssetsIdRouteRouteWithChildren
  '/dashboard/clients/$id': typeof DashboardClientsIdRouteRouteWithChildren
  '/dashboard/assets/new': typeof DashboardAssetsNewRoute
  '/dashboard/clients/new': typeof DashboardClientsNewRoute
  '/dashboard/jobs/new': typeof DashboardJobsNewRoute
  '/dashboard/methods/new': typeof DashboardMethodsNewRoute
  '/dashboard/services/new': typeof DashboardServicesNewRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/dashboard/settings/authentication': typeof DashboardSettingsAuthenticationRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/danger': typeof DashboardSettingsDangerRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/organization': typeof DashboardSettingsOrganizationRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/standards/new': typeof DashboardStandardsNewRoute
  '/dashboard/assets/': typeof DashboardAssetsIndexRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
  '/dashboard/jobs/': typeof DashboardJobsIndexRoute
  '/dashboard/methods/': typeof DashboardMethodsIndexRoute
  '/dashboard/services/': typeof DashboardServicesIndexRoute
  '/dashboard/standards/': typeof DashboardStandardsIndexRoute
  '/dashboard/assets/$id/edit': typeof DashboardAssetsIdEditRoute
  '/dashboard/clients/$id/assets': typeof DashboardClientsIdAssetsRoute
  '/dashboard/clients/$id/calibrations': typeof DashboardClientsIdCalibrationsRoute
  '/dashboard/clients/$id/compliance': typeof DashboardClientsIdComplianceRoute
  '/dashboard/clients/$id/info': typeof DashboardClientsIdInfoRoute
  '/dashboard/clients/$id/users': typeof DashboardClientsIdUsersRoute
  '/dashboard/jobs/$id/execute': typeof DashboardJobsIdExecuteRoute
  '/dashboard/methods/$id/edit': typeof DashboardMethodsIdEditRoute
  '/dashboard/services/$id/edit': typeof DashboardServicesIdEditRoute
  '/dashboard/standards/$id/edit': typeof DashboardStandardsIdEditRoute
  '/dashboard/assets/$id/': typeof DashboardAssetsIdIndexRoute
  '/dashboard/clients/$id/': typeof DashboardClientsIdIndexRoute
  '/dashboard/jobs/$id/': typeof DashboardJobsIdIndexRoute
  '/dashboard/methods/$id/': typeof DashboardMethodsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/assets'
    | '/dashboard/clients'
    | '/dashboard/jobs'
    | '/dashboard/methods'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/standards'
    | '/accept-invitation/$id'
    | '/dashboard/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/assets/$id'
    | '/dashboard/clients/$id'
    | '/dashboard/assets/new'
    | '/dashboard/clients/new'
    | '/dashboard/jobs/new'
    | '/dashboard/methods/new'
    | '/dashboard/services/new'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/authentication'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/danger'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/organization'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/security'
    | '/dashboard/standards/new'
    | '/dashboard/assets/'
    | '/dashboard/clients/'
    | '/dashboard/jobs/'
    | '/dashboard/methods/'
    | '/dashboard/services/'
    | '/dashboard/standards/'
    | '/dashboard/assets/$id/edit'
    | '/dashboard/clients/$id/assets'
    | '/dashboard/clients/$id/calibrations'
    | '/dashboard/clients/$id/compliance'
    | '/dashboard/clients/$id/info'
    | '/dashboard/clients/$id/users'
    | '/dashboard/jobs/$id/execute'
    | '/dashboard/methods/$id/edit'
    | '/dashboard/services/$id/edit'
    | '/dashboard/standards/$id/edit'
    | '/dashboard/assets/$id/'
    | '/dashboard/clients/$id/'
    | '/dashboard/jobs/$id'
    | '/dashboard/methods/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/settings'
    | '/accept-invitation/$id'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/assets/new'
    | '/dashboard/clients/new'
    | '/dashboard/jobs/new'
    | '/dashboard/methods/new'
    | '/dashboard/services/new'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/authentication'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/danger'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/organization'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/security'
    | '/dashboard/standards/new'
    | '/dashboard/assets'
    | '/dashboard/clients'
    | '/dashboard/jobs'
    | '/dashboard/methods'
    | '/dashboard/services'
    | '/dashboard/standards'
    | '/dashboard/assets/$id/edit'
    | '/dashboard/clients/$id/assets'
    | '/dashboard/clients/$id/calibrations'
    | '/dashboard/clients/$id/compliance'
    | '/dashboard/clients/$id/info'
    | '/dashboard/clients/$id/users'
    | '/dashboard/jobs/$id/execute'
    | '/dashboard/methods/$id/edit'
    | '/dashboard/services/$id/edit'
    | '/dashboard/standards/$id/edit'
    | '/dashboard/assets/$id'
    | '/dashboard/clients/$id'
    | '/dashboard/jobs/$id'
    | '/dashboard/methods/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/assets'
    | '/dashboard/clients'
    | '/dashboard/jobs'
    | '/dashboard/methods'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/standards'
    | '/accept-invitation/$id'
    | '/dashboard/'
    | '/sign-in/'
    | '/sign-up/'
    | '/dashboard/assets/$id'
    | '/dashboard/clients/$id'
    | '/dashboard/assets/new'
    | '/dashboard/clients/new'
    | '/dashboard/jobs/new'
    | '/dashboard/methods/new'
    | '/dashboard/services/new'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/authentication'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/danger'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/organization'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/security'
    | '/dashboard/standards/new'
    | '/dashboard/assets/'
    | '/dashboard/clients/'
    | '/dashboard/jobs/'
    | '/dashboard/methods/'
    | '/dashboard/services/'
    | '/dashboard/standards/'
    | '/dashboard/assets/$id/edit'
    | '/dashboard/clients/$id/assets'
    | '/dashboard/clients/$id/calibrations'
    | '/dashboard/clients/$id/compliance'
    | '/dashboard/clients/$id/info'
    | '/dashboard/clients/$id/users'
    | '/dashboard/jobs/$id/execute'
    | '/dashboard/methods/$id/edit'
    | '/dashboard/services/$id/edit'
    | '/dashboard/standards/$id/edit'
    | '/dashboard/assets/$id/'
    | '/dashboard/clients/$id/'
    | '/dashboard/jobs/$id/'
    | '/dashboard/methods/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AcceptInvitationIdRoute: typeof AcceptInvitationIdRoute
  SignInIndexRoute: typeof SignInIndexRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/accept-invitation/$id': {
      id: '/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof AcceptInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/standards': {
      id: '/dashboard/standards'
      path: '/standards'
      fullPath: '/dashboard/standards'
      preLoaderRoute: typeof DashboardStandardsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/methods': {
      id: '/dashboard/methods'
      path: '/methods'
      fullPath: '/dashboard/methods'
      preLoaderRoute: typeof DashboardMethodsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/clients': {
      id: '/dashboard/clients'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardClientsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/assets': {
      id: '/dashboard/assets'
      path: '/assets'
      fullPath: '/dashboard/assets'
      preLoaderRoute: typeof DashboardAssetsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/standards/': {
      id: '/dashboard/standards/'
      path: '/'
      fullPath: '/dashboard/standards/'
      preLoaderRoute: typeof DashboardStandardsIndexRouteImport
      parentRoute: typeof DashboardStandardsRouteRoute
    }
    '/dashboard/services/': {
      id: '/dashboard/services/'
      path: '/'
      fullPath: '/dashboard/services/'
      preLoaderRoute: typeof DashboardServicesIndexRouteImport
      parentRoute: typeof DashboardServicesRouteRoute
    }
    '/dashboard/methods/': {
      id: '/dashboard/methods/'
      path: '/'
      fullPath: '/dashboard/methods/'
      preLoaderRoute: typeof DashboardMethodsIndexRouteImport
      parentRoute: typeof DashboardMethodsRouteRoute
    }
    '/dashboard/jobs/': {
      id: '/dashboard/jobs/'
      path: '/'
      fullPath: '/dashboard/jobs/'
      preLoaderRoute: typeof DashboardJobsIndexRouteImport
      parentRoute: typeof DashboardJobsRouteRoute
    }
    '/dashboard/clients/': {
      id: '/dashboard/clients/'
      path: '/'
      fullPath: '/dashboard/clients/'
      preLoaderRoute: typeof DashboardClientsIndexRouteImport
      parentRoute: typeof DashboardClientsRouteRoute
    }
    '/dashboard/assets/': {
      id: '/dashboard/assets/'
      path: '/'
      fullPath: '/dashboard/assets/'
      preLoaderRoute: typeof DashboardAssetsIndexRouteImport
      parentRoute: typeof DashboardAssetsRouteRoute
    }
    '/dashboard/standards/new': {
      id: '/dashboard/standards/new'
      path: '/new'
      fullPath: '/dashboard/standards/new'
      preLoaderRoute: typeof DashboardStandardsNewRouteImport
      parentRoute: typeof DashboardStandardsRouteRoute
    }
    '/dashboard/settings/security': {
      id: '/dashboard/settings/security'
      path: '/security'
      fullPath: '/dashboard/settings/security'
      preLoaderRoute: typeof DashboardSettingsSecurityRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/profile': {
      id: '/dashboard/settings/profile'
      path: '/profile'
      fullPath: '/dashboard/settings/profile'
      preLoaderRoute: typeof DashboardSettingsProfileRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/organization': {
      id: '/dashboard/settings/organization'
      path: '/organization'
      fullPath: '/dashboard/settings/organization'
      preLoaderRoute: typeof DashboardSettingsOrganizationRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/notifications': {
      id: '/dashboard/settings/notifications'
      path: '/notifications'
      fullPath: '/dashboard/settings/notifications'
      preLoaderRoute: typeof DashboardSettingsNotificationsRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/danger': {
      id: '/dashboard/settings/danger'
      path: '/danger'
      fullPath: '/dashboard/settings/danger'
      preLoaderRoute: typeof DashboardSettingsDangerRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/billing': {
      id: '/dashboard/settings/billing'
      path: '/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof DashboardSettingsBillingRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/authentication': {
      id: '/dashboard/settings/authentication'
      path: '/authentication'
      fullPath: '/dashboard/settings/authentication'
      preLoaderRoute: typeof DashboardSettingsAuthenticationRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/appearance': {
      id: '/dashboard/settings/appearance'
      path: '/appearance'
      fullPath: '/dashboard/settings/appearance'
      preLoaderRoute: typeof DashboardSettingsAppearanceRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/services/new': {
      id: '/dashboard/services/new'
      path: '/new'
      fullPath: '/dashboard/services/new'
      preLoaderRoute: typeof DashboardServicesNewRouteImport
      parentRoute: typeof DashboardServicesRouteRoute
    }
    '/dashboard/methods/new': {
      id: '/dashboard/methods/new'
      path: '/new'
      fullPath: '/dashboard/methods/new'
      preLoaderRoute: typeof DashboardMethodsNewRouteImport
      parentRoute: typeof DashboardMethodsRouteRoute
    }
    '/dashboard/jobs/new': {
      id: '/dashboard/jobs/new'
      path: '/new'
      fullPath: '/dashboard/jobs/new'
      preLoaderRoute: typeof DashboardJobsNewRouteImport
      parentRoute: typeof DashboardJobsRouteRoute
    }
    '/dashboard/clients/new': {
      id: '/dashboard/clients/new'
      path: '/new'
      fullPath: '/dashboard/clients/new'
      preLoaderRoute: typeof DashboardClientsNewRouteImport
      parentRoute: typeof DashboardClientsRouteRoute
    }
    '/dashboard/assets/new': {
      id: '/dashboard/assets/new'
      path: '/new'
      fullPath: '/dashboard/assets/new'
      preLoaderRoute: typeof DashboardAssetsNewRouteImport
      parentRoute: typeof DashboardAssetsRouteRoute
    }
    '/dashboard/clients/$id': {
      id: '/dashboard/clients/$id'
      path: '/$id'
      fullPath: '/dashboard/clients/$id'
      preLoaderRoute: typeof DashboardClientsIdRouteRouteImport
      parentRoute: typeof DashboardClientsRouteRoute
    }
    '/dashboard/assets/$id': {
      id: '/dashboard/assets/$id'
      path: '/$id'
      fullPath: '/dashboard/assets/$id'
      preLoaderRoute: typeof DashboardAssetsIdRouteRouteImport
      parentRoute: typeof DashboardAssetsRouteRoute
    }
    '/dashboard/methods/$id/': {
      id: '/dashboard/methods/$id/'
      path: '/$id'
      fullPath: '/dashboard/methods/$id'
      preLoaderRoute: typeof DashboardMethodsIdIndexRouteImport
      parentRoute: typeof DashboardMethodsRouteRoute
    }
    '/dashboard/jobs/$id/': {
      id: '/dashboard/jobs/$id/'
      path: '/$id'
      fullPath: '/dashboard/jobs/$id'
      preLoaderRoute: typeof DashboardJobsIdIndexRouteImport
      parentRoute: typeof DashboardJobsRouteRoute
    }
    '/dashboard/clients/$id/': {
      id: '/dashboard/clients/$id/'
      path: '/'
      fullPath: '/dashboard/clients/$id/'
      preLoaderRoute: typeof DashboardClientsIdIndexRouteImport
      parentRoute: typeof DashboardClientsIdRouteRoute
    }
    '/dashboard/assets/$id/': {
      id: '/dashboard/assets/$id/'
      path: '/'
      fullPath: '/dashboard/assets/$id/'
      preLoaderRoute: typeof DashboardAssetsIdIndexRouteImport
      parentRoute: typeof DashboardAssetsIdRouteRoute
    }
    '/dashboard/standards/$id/edit': {
      id: '/dashboard/standards/$id/edit'
      path: '/$id/edit'
      fullPath: '/dashboard/standards/$id/edit'
      preLoaderRoute: typeof DashboardStandardsIdEditRouteImport
      parentRoute: typeof DashboardStandardsRouteRoute
    }
    '/dashboard/services/$id/edit': {
      id: '/dashboard/services/$id/edit'
      path: '/$id/edit'
      fullPath: '/dashboard/services/$id/edit'
      preLoaderRoute: typeof DashboardServicesIdEditRouteImport
      parentRoute: typeof DashboardServicesRouteRoute
    }
    '/dashboard/methods/$id/edit': {
      id: '/dashboard/methods/$id/edit'
      path: '/$id/edit'
      fullPath: '/dashboard/methods/$id/edit'
      preLoaderRoute: typeof DashboardMethodsIdEditRouteImport
      parentRoute: typeof DashboardMethodsRouteRoute
    }
    '/dashboard/jobs/$id/execute': {
      id: '/dashboard/jobs/$id/execute'
      path: '/$id/execute'
      fullPath: '/dashboard/jobs/$id/execute'
      preLoaderRoute: typeof DashboardJobsIdExecuteRouteImport
      parentRoute: typeof DashboardJobsRouteRoute
    }
    '/dashboard/clients/$id/users': {
      id: '/dashboard/clients/$id/users'
      path: '/users'
      fullPath: '/dashboard/clients/$id/users'
      preLoaderRoute: typeof DashboardClientsIdUsersRouteImport
      parentRoute: typeof DashboardClientsIdRouteRoute
    }
    '/dashboard/clients/$id/info': {
      id: '/dashboard/clients/$id/info'
      path: '/info'
      fullPath: '/dashboard/clients/$id/info'
      preLoaderRoute: typeof DashboardClientsIdInfoRouteImport
      parentRoute: typeof DashboardClientsIdRouteRoute
    }
    '/dashboard/clients/$id/compliance': {
      id: '/dashboard/clients/$id/compliance'
      path: '/compliance'
      fullPath: '/dashboard/clients/$id/compliance'
      preLoaderRoute: typeof DashboardClientsIdComplianceRouteImport
      parentRoute: typeof DashboardClientsIdRouteRoute
    }
    '/dashboard/clients/$id/calibrations': {
      id: '/dashboard/clients/$id/calibrations'
      path: '/calibrations'
      fullPath: '/dashboard/clients/$id/calibrations'
      preLoaderRoute: typeof DashboardClientsIdCalibrationsRouteImport
      parentRoute: typeof DashboardClientsIdRouteRoute
    }
    '/dashboard/clients/$id/assets': {
      id: '/dashboard/clients/$id/assets'
      path: '/assets'
      fullPath: '/dashboard/clients/$id/assets'
      preLoaderRoute: typeof DashboardClientsIdAssetsRouteImport
      parentRoute: typeof DashboardClientsIdRouteRoute
    }
    '/dashboard/assets/$id/edit': {
      id: '/dashboard/assets/$id/edit'
      path: '/edit'
      fullPath: '/dashboard/assets/$id/edit'
      preLoaderRoute: typeof DashboardAssetsIdEditRouteImport
      parentRoute: typeof DashboardAssetsIdRouteRoute
    }
  }
}

interface DashboardAssetsIdRouteRouteChildren {
  DashboardAssetsIdEditRoute: typeof DashboardAssetsIdEditRoute
  DashboardAssetsIdIndexRoute: typeof DashboardAssetsIdIndexRoute
}

const DashboardAssetsIdRouteRouteChildren: DashboardAssetsIdRouteRouteChildren =
  {
    DashboardAssetsIdEditRoute: DashboardAssetsIdEditRoute,
    DashboardAssetsIdIndexRoute: DashboardAssetsIdIndexRoute,
  }

const DashboardAssetsIdRouteRouteWithChildren =
  DashboardAssetsIdRouteRoute._addFileChildren(
    DashboardAssetsIdRouteRouteChildren,
  )

interface DashboardAssetsRouteRouteChildren {
  DashboardAssetsIdRouteRoute: typeof DashboardAssetsIdRouteRouteWithChildren
  DashboardAssetsNewRoute: typeof DashboardAssetsNewRoute
  DashboardAssetsIndexRoute: typeof DashboardAssetsIndexRoute
}

const DashboardAssetsRouteRouteChildren: DashboardAssetsRouteRouteChildren = {
  DashboardAssetsIdRouteRoute: DashboardAssetsIdRouteRouteWithChildren,
  DashboardAssetsNewRoute: DashboardAssetsNewRoute,
  DashboardAssetsIndexRoute: DashboardAssetsIndexRoute,
}

const DashboardAssetsRouteRouteWithChildren =
  DashboardAssetsRouteRoute._addFileChildren(DashboardAssetsRouteRouteChildren)

interface DashboardClientsIdRouteRouteChildren {
  DashboardClientsIdAssetsRoute: typeof DashboardClientsIdAssetsRoute
  DashboardClientsIdCalibrationsRoute: typeof DashboardClientsIdCalibrationsRoute
  DashboardClientsIdComplianceRoute: typeof DashboardClientsIdComplianceRoute
  DashboardClientsIdInfoRoute: typeof DashboardClientsIdInfoRoute
  DashboardClientsIdUsersRoute: typeof DashboardClientsIdUsersRoute
  DashboardClientsIdIndexRoute: typeof DashboardClientsIdIndexRoute
}

const DashboardClientsIdRouteRouteChildren: DashboardClientsIdRouteRouteChildren =
  {
    DashboardClientsIdAssetsRoute: DashboardClientsIdAssetsRoute,
    DashboardClientsIdCalibrationsRoute: DashboardClientsIdCalibrationsRoute,
    DashboardClientsIdComplianceRoute: DashboardClientsIdComplianceRoute,
    DashboardClientsIdInfoRoute: DashboardClientsIdInfoRoute,
    DashboardClientsIdUsersRoute: DashboardClientsIdUsersRoute,
    DashboardClientsIdIndexRoute: DashboardClientsIdIndexRoute,
  }

const DashboardClientsIdRouteRouteWithChildren =
  DashboardClientsIdRouteRoute._addFileChildren(
    DashboardClientsIdRouteRouteChildren,
  )

interface DashboardClientsRouteRouteChildren {
  DashboardClientsIdRouteRoute: typeof DashboardClientsIdRouteRouteWithChildren
  DashboardClientsNewRoute: typeof DashboardClientsNewRoute
  DashboardClientsIndexRoute: typeof DashboardClientsIndexRoute
}

const DashboardClientsRouteRouteChildren: DashboardClientsRouteRouteChildren = {
  DashboardClientsIdRouteRoute: DashboardClientsIdRouteRouteWithChildren,
  DashboardClientsNewRoute: DashboardClientsNewRoute,
  DashboardClientsIndexRoute: DashboardClientsIndexRoute,
}

const DashboardClientsRouteRouteWithChildren =
  DashboardClientsRouteRoute._addFileChildren(
    DashboardClientsRouteRouteChildren,
  )

interface DashboardJobsRouteRouteChildren {
  DashboardJobsNewRoute: typeof DashboardJobsNewRoute
  DashboardJobsIndexRoute: typeof DashboardJobsIndexRoute
  DashboardJobsIdExecuteRoute: typeof DashboardJobsIdExecuteRoute
  DashboardJobsIdIndexRoute: typeof DashboardJobsIdIndexRoute
}

const DashboardJobsRouteRouteChildren: DashboardJobsRouteRouteChildren = {
  DashboardJobsNewRoute: DashboardJobsNewRoute,
  DashboardJobsIndexRoute: DashboardJobsIndexRoute,
  DashboardJobsIdExecuteRoute: DashboardJobsIdExecuteRoute,
  DashboardJobsIdIndexRoute: DashboardJobsIdIndexRoute,
}

const DashboardJobsRouteRouteWithChildren =
  DashboardJobsRouteRoute._addFileChildren(DashboardJobsRouteRouteChildren)

interface DashboardMethodsRouteRouteChildren {
  DashboardMethodsNewRoute: typeof DashboardMethodsNewRoute
  DashboardMethodsIndexRoute: typeof DashboardMethodsIndexRoute
  DashboardMethodsIdEditRoute: typeof DashboardMethodsIdEditRoute
  DashboardMethodsIdIndexRoute: typeof DashboardMethodsIdIndexRoute
}

const DashboardMethodsRouteRouteChildren: DashboardMethodsRouteRouteChildren = {
  DashboardMethodsNewRoute: DashboardMethodsNewRoute,
  DashboardMethodsIndexRoute: DashboardMethodsIndexRoute,
  DashboardMethodsIdEditRoute: DashboardMethodsIdEditRoute,
  DashboardMethodsIdIndexRoute: DashboardMethodsIdIndexRoute,
}

const DashboardMethodsRouteRouteWithChildren =
  DashboardMethodsRouteRoute._addFileChildren(
    DashboardMethodsRouteRouteChildren,
  )

interface DashboardServicesRouteRouteChildren {
  DashboardServicesNewRoute: typeof DashboardServicesNewRoute
  DashboardServicesIndexRoute: typeof DashboardServicesIndexRoute
  DashboardServicesIdEditRoute: typeof DashboardServicesIdEditRoute
}

const DashboardServicesRouteRouteChildren: DashboardServicesRouteRouteChildren =
  {
    DashboardServicesNewRoute: DashboardServicesNewRoute,
    DashboardServicesIndexRoute: DashboardServicesIndexRoute,
    DashboardServicesIdEditRoute: DashboardServicesIdEditRoute,
  }

const DashboardServicesRouteRouteWithChildren =
  DashboardServicesRouteRoute._addFileChildren(
    DashboardServicesRouteRouteChildren,
  )

interface DashboardSettingsRouteRouteChildren {
  DashboardSettingsAppearanceRoute: typeof DashboardSettingsAppearanceRoute
  DashboardSettingsAuthenticationRoute: typeof DashboardSettingsAuthenticationRoute
  DashboardSettingsBillingRoute: typeof DashboardSettingsBillingRoute
  DashboardSettingsDangerRoute: typeof DashboardSettingsDangerRoute
  DashboardSettingsNotificationsRoute: typeof DashboardSettingsNotificationsRoute
  DashboardSettingsOrganizationRoute: typeof DashboardSettingsOrganizationRoute
  DashboardSettingsProfileRoute: typeof DashboardSettingsProfileRoute
  DashboardSettingsSecurityRoute: typeof DashboardSettingsSecurityRoute
}

const DashboardSettingsRouteRouteChildren: DashboardSettingsRouteRouteChildren =
  {
    DashboardSettingsAppearanceRoute: DashboardSettingsAppearanceRoute,
    DashboardSettingsAuthenticationRoute: DashboardSettingsAuthenticationRoute,
    DashboardSettingsBillingRoute: DashboardSettingsBillingRoute,
    DashboardSettingsDangerRoute: DashboardSettingsDangerRoute,
    DashboardSettingsNotificationsRoute: DashboardSettingsNotificationsRoute,
    DashboardSettingsOrganizationRoute: DashboardSettingsOrganizationRoute,
    DashboardSettingsProfileRoute: DashboardSettingsProfileRoute,
    DashboardSettingsSecurityRoute: DashboardSettingsSecurityRoute,
  }

const DashboardSettingsRouteRouteWithChildren =
  DashboardSettingsRouteRoute._addFileChildren(
    DashboardSettingsRouteRouteChildren,
  )

interface DashboardStandardsRouteRouteChildren {
  DashboardStandardsNewRoute: typeof DashboardStandardsNewRoute
  DashboardStandardsIndexRoute: typeof DashboardStandardsIndexRoute
  DashboardStandardsIdEditRoute: typeof DashboardStandardsIdEditRoute
}

const DashboardStandardsRouteRouteChildren: DashboardStandardsRouteRouteChildren =
  {
    DashboardStandardsNewRoute: DashboardStandardsNewRoute,
    DashboardStandardsIndexRoute: DashboardStandardsIndexRoute,
    DashboardStandardsIdEditRoute: DashboardStandardsIdEditRoute,
  }

const DashboardStandardsRouteRouteWithChildren =
  DashboardStandardsRouteRoute._addFileChildren(
    DashboardStandardsRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardAssetsRouteRoute: typeof DashboardAssetsRouteRouteWithChildren
  DashboardClientsRouteRoute: typeof DashboardClientsRouteRouteWithChildren
  DashboardJobsRouteRoute: typeof DashboardJobsRouteRouteWithChildren
  DashboardMethodsRouteRoute: typeof DashboardMethodsRouteRouteWithChildren
  DashboardServicesRouteRoute: typeof DashboardServicesRouteRouteWithChildren
  DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRouteWithChildren
  DashboardStandardsRouteRoute: typeof DashboardStandardsRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAssetsRouteRoute: DashboardAssetsRouteRouteWithChildren,
  DashboardClientsRouteRoute: DashboardClientsRouteRouteWithChildren,
  DashboardJobsRouteRoute: DashboardJobsRouteRouteWithChildren,
  DashboardMethodsRouteRoute: DashboardMethodsRouteRouteWithChildren,
  DashboardServicesRouteRoute: DashboardServicesRouteRouteWithChildren,
  DashboardSettingsRouteRoute: DashboardSettingsRouteRouteWithChildren,
  DashboardStandardsRouteRoute: DashboardStandardsRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AcceptInvitationIdRoute: AcceptInvitationIdRoute,
  SignInIndexRoute: SignInIndexRoute,
  SignUpIndexRoute: SignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
