import type { Hono } from "hono";
import type { BlankEnv } from "hono/types";

type RpcScalar = string | number | boolean | null | undefined;
type RpcQuery = Record<string, RpcScalar | RpcScalar[]>;

type PathParams<Path extends string> =
  Path extends `${string}:${infer Param}/${infer Rest}`
    ? { [Key in Param | keyof PathParams<Rest>]: string }
    : Path extends `${string}:${infer Param}`
      ? { [Key in Param]: string }
      : Record<never, never>;

type RpcInput<Path extends string> = keyof PathParams<Path> extends never
  ? {
      json?: unknown;
      query?: RpcQuery;
    }
  : {
      param: PathParams<Path>;
      json?: unknown;
      query?: RpcQuery;
    };

type JsonEndpoint<Path extends string> = {
  input: RpcInput<Path>;
  output: unknown;
  outputFormat: "json";
  status: 200;
};

type RpcRoute<Path extends string> = {
  $all: JsonEndpoint<Path>;
};

// Keep the browser-facing Hono contract server-free. Importing apps/api here
// pulls route handlers and runtime dependencies back across the package boundary.
type ApiRoutePath =
  | "/api/api-keys"
  | "/api/api-keys/:id/revoke"
  | "/api/api-keys/:id/rotate"
  | "/api/asset-types"
  | "/api/assets"
  | "/api/assets/:id"
  | "/api/assets/:id/audit-log"
  | "/api/backoffice/access"
  | "/api/backoffice/account-tasks"
  | "/api/backoffice/account-tasks/:id/complete"
  | "/api/backoffice/audit-log"
  | "/api/backoffice/bootstrap"
  | "/api/backoffice/commercial/billing-contacts"
  | "/api/backoffice/commercial/customers/sync"
  | "/api/backoffice/commercial/offers"
  | "/api/backoffice/commercial/offers/:id/cancel"
  | "/api/backoffice/commercial/offers/:id/reissue"
  | "/api/backoffice/commercial/offers/preview"
  | "/api/backoffice/commercial/organizations"
  | "/api/backoffice/commercial/organizations/:id/context"
  | "/api/backoffice/customer-success/organizations/:organizationId/blocker"
  | "/api/backoffice/customer-success/organizations/:organizationId/next-action"
  | "/api/backoffice/customer-success/organizations/:organizationId/profile"
  | "/api/backoffice/customer-success/organizations/:organizationId/requests"
  | "/api/backoffice/customer-success/requests/:requestId/assign"
  | "/api/backoffice/customer-success/requests/:requestId/escalate"
  | "/api/backoffice/customer-success/requests/:requestId/respond"
  | "/api/backoffice/customer-success/requests/:requestId/status"
  | "/api/backoffice/impersonation/stop"
  | "/api/backoffice/integrations/health"
  | "/api/backoffice/labs"
  | "/api/backoffice/entitlement-overrides/:id/revoke"
  | "/api/backoffice/organizations"
  | "/api/backoffice/organizations/:id"
  | "/api/backoffice/organizations/:id/entitlement-overrides"
  | "/api/backoffice/organizations/:id/lifecycle"
  | "/api/backoffice/presence"
  | "/api/backoffice/support/queue"
  | "/api/backoffice/users"
  | "/api/backoffice/users/:id"
  | "/api/backoffice/users/:id/activity"
  | "/api/backoffice/users/:id/ban"
  | "/api/backoffice/users/:id/impersonate"
  | "/api/backoffice/users/:id/password-reset"
  | "/api/backoffice/users/:id/role"
  | "/api/backoffice/users/:id/sessions"
  | "/api/backoffice/users/:id/sessions/revoke"
  | "/api/backoffice/users/:id/unban"
  | "/api/backoffice/vitals"
  | "/api/billing/access"
  | "/api/billing/payments"
  | "/api/billing/subscription"
  | "/api/calibration-requests"
  | "/api/calibration-requests/:id"
  | "/api/calibration-requests/:id/approve"
  | "/api/calibration-requests/:id/convert"
  | "/api/calibration-requests/:id/reject"
  | "/api/calibration-requests/:id/review"
  | "/api/capa"
  | "/api/capa/:id"
  | "/api/capa/:id/audit-log"
  | "/api/capa/:id/close"
  | "/api/capa/:id/implement"
  | "/api/capa/:id/label"
  | "/api/capa/:id/verify"
  | "/api/capa/summary"
  | "/api/authorized-signatories"
  | "/api/authorized-signatories/:id/revoke"
  | "/api/certificate-numbering"
  | "/api/certificate-templates"
  | "/api/certificate-templates/:id/default"
  | "/api/certificate-templates/:id/duplicate"
  | "/api/competences"
  | "/api/competences/:id"
  | "/api/competences/:id/assign-training"
  | "/api/competences/:id/audit-log"
  | "/api/competences/:id/cancel"
  | "/api/competences/:id/evaluate"
  | "/api/competences/:id/label"
  | "/api/competences/:id/renew"
  | "/api/competences/matrix"
  | "/api/customer-success/profile"
  | "/api/customer-success/requests"
  | "/api/customers"
  | "/api/customers/cnpj-lookup/:cnpj"
  | "/api/customers/:id"
  | "/api/customers/:id/audit-log"
  | "/api/customers/:id/compliance"
  | "/api/customers/:id/invitations"
  | "/api/customers/:id/invitations/:invId"
  | "/api/customers/:id/invitations/:invId/resend"
  | "/api/customers/:id/members"
  | "/api/customers/:id/members/:memberId"
  | "/api/customer-groups"
  | "/api/customer-groups/:id"
  | "/api/customer-groups/:id/branches"
  | "/api/customer-groups/:id/branches/:customerId"
  | "/api/customer-groups/:id/members"
  | "/api/customer-groups/:id/members/:memberId"
  | "/api/customer-groups/:id/invitations"
  | "/api/customer-groups/:id/invitations/:invId"
  | "/api/customer-groups/:id/invitations/:invId/resend"
  | "/api/dashboard/stats"
  | "/api/environmental-limits"
  | "/api/environmental-limits/:id"
  | "/api/environmental-limits/effective/:assetTypeId"
  | "/api/finance/access"
  | "/api/finance/automatic-send-rules"
  | "/api/finance/automatic-send-rules/:id"
  | "/api/finance/billing-readiness"
  | "/api/finance/billing-readiness/send"
  | "/api/finance/certificate-releases/:calibrationJobId"
  | "/api/finance/certificate-releases/:calibrationJobId/release-by-exception"
  | "/api/finance/certificate-release-policies"
  | "/api/finance/certificate-release-policies/:id"
  | "/api/finance/contracts"
  | "/api/finance/contracts/:id"
  | "/api/finance/contracts/:id/activate"
  | "/api/finance/contracts/:id/cancel"
  | "/api/finance/customers/:customerId/timeline"
  | "/api/finance/documents"
  | "/api/finance/documents/:id"
  | "/api/finance/documents/:id/issue"
  | "/api/finance/documents/:id/void"
  | "/api/finance/documents/eligible-jobs"
  | "/api/finance/erp/documents/:id/export"
  | "/api/finance/erp/exports"
  | "/api/finance/installments/:id/receive"
  | "/api/finance/cash-forecast"
  | "/api/finance/margin-dashboards"
  | "/api/finance/operations-to-cash"
  | "/api/finance/overview"
  | "/api/finance/revenue-leakage"
  | "/api/finance/receipts"
  | "/api/finance/service-orders/:serviceOrderId/status"
  | "/api/integrations"
  | "/api/integrations/drift"
  | "/api/integrations/drift/:linkId/acknowledge"
  | "/api/integrations/:id"
  | "/api/integrations/:id/conta-azul/catalog/accounts"
  | "/api/integrations/:id/conta-azul/catalog/:catalog"
  | "/api/integrations/:id/conta-azul/catalog/categories"
  | "/api/integrations/:id/conta-azul/catalog/cost-centers"
  | "/api/integrations/:id/conta-azul/config"
  | "/api/integrations/:id/conta-azul/disconnect"
  | "/api/integrations/:id/conta-azul/link-mdfe"
  | "/api/integrations/:id/conta-azul/poll"
  | "/api/integrations/:id/conta-azul/poll-drift"
  | "/api/integrations/:id/conta-azul/poll-fiscal"
  | "/api/integrations/:id/conta-azul/poll-payables"
  | "/api/integrations/:id/conta-azul/poll-protocols"
  | "/api/integrations/:id/conta-azul/refresh"
  | "/api/integrations/:id/conta-azul/schedule"
  | "/api/integrations/:id/events"
  | "/api/integrations/:id/overview"
  | "/api/integrations/:id/runs"
  | "/api/integrations/:id/runs/:runId/items"
  | "/api/integrations/:id/runs/:runId/retry"
  | "/api/integrations/:id/schedule"
  | "/api/integrations/:id/sync"
  | "/api/integrations/:id/sync/preview"
  | "/api/integrations/:id/toggle"
  | "/api/integrations/:id/validate"
  | "/api/integrations/conta-azul/oauth/callback"
  | "/api/integrations/conta-azul/oauth/start"
  | "/api/invitations/:id/request-setup-link"
  | "/api/lab-setup/:token"
  | "/api/lab-setup/:token/complete"
  | "/api/lab-setup/:token/request-magic-link"
  | "/api/lab-setup/:token/request-otp"
  | "/api/jobs"
  | "/api/jobs/:id"
  | "/api/jobs/:id/amend"
  | "/api/jobs/:id/approve"
  | "/api/jobs/:id/assign"
  | "/api/jobs/:id/download"
  | "/api/jobs/:id/download-label"
  | "/api/jobs/:id/execute"
  | "/api/jobs/:id/generate-label"
  | "/api/jobs/:id/label-commands"
  | "/api/jobs/:id/reject"
  | "/api/jobs/:id/submit"
  | "/api/jobs/technicians/list"
  | "/api/materials"
  | "/api/materials/:id"
  | "/api/materials/:id/stock"
  | "/api/methods"
  | "/api/methods/from-template"
  | "/api/methods/templates"
  | "/api/methods/:id"
  | "/api/methods/:id/archive"
  | "/api/methods/:id/audit"
  | "/api/methods/:id/new-version"
  | "/api/methods/:id/quality-approve"
  | "/api/methods/:id/return-to-draft"
  | "/api/methods/:id/technical-review"
  | "/api/nc"
  | "/api/nc/:id"
  | "/api/nc/:id/audit-log"
  | "/api/nc/:id/disposition"
  | "/api/nc/:id/escalate-to-capa"
  | "/api/nc/:id/label"
  | "/api/nc/:id/resolve"
  | "/api/nc/summary"
  | "/api/notifications"
  | "/api/notifications/mark-all-read"
  | "/api/notifications/mark-read"
  | "/api/notifications/preferences"
  | "/api/notifications/unread-count"
  | "/api/portal-domains"
  | "/api/portal-domains/activate"
  | "/api/portal-domains/verify"
  | "/api/portal/service-orders/:id/financial-summary"
  | "/api/public/commercial-checkout/:token"
  | "/api/public/commercial-checkout/:token/start"
  | "/api/public/commercial-checkout/:token/status"
  | "/api/reports/consolidated/comparison"
  | "/api/reports/consolidated/executive-overview"
  | "/api/reports/consolidated/trend"
  | "/api/service-orders"
  | "/api/service-orders/:id"
  | "/api/service-orders/:id/deliver"
  | "/api/service-orders/:id/delivery-document"
  | "/api/service-orders/:id/delivery-document.pdf"
  | "/api/service-orders/:id/evaluations"
  | "/api/service-orders/:id/evaluations/:evaluationId"
  | "/api/service-orders/:id/execution/finish"
  | "/api/service-orders/:id/intake-document"
  | "/api/service-orders/:id/intake-document.pdf"
  | "/api/service-orders/:id/quotes"
  | "/api/service-orders/:id/quotes/:quoteId/send"
  | "/api/service-orders/:id/repair-mark"
  | "/api/service-orders/:id/tag"
  | "/api/service-orders/:id/tag.pdf"
  | "/api/service-orders/pending-calibration"
  | "/api/services"
  | "/api/services/:id"
  | "/api/services/:id/audit-log"
  | "/api/sessions/revoke"
  | "/api/signatures/my-signature"
  | "/api/signing/certificates"
  | "/api/signing/policy"
  | "/api/signing/certificates/:id"
  | "/api/signing/certificates/:id/set-default"
  | "/api/sso/providers"
  | "/api/sso/providers/:providerId"
  | "/api/sso/providers/:providerId/request-domain-verification"
  | "/api/sso/providers/:providerId/verify-domain"
  | "/api/sso/start"
  | "/api/standards"
  | "/api/standards/composition-profiles"
  | "/api/standards/composition-profiles/:id"
  | "/api/standards/:id"
  | "/api/standards/:id/audit-log"
  | "/api/standards/:id/certificate-document"
  | "/api/standards/:id/certificate-document/download"
  | "/api/standards/:id/renew"
  | "/api/training-records"
  | "/api/units"
  | "/api/units/admin/activity"
  | "/api/units/admin/members"
  | "/api/units/admin/members/:memberId/assignments"
  | "/api/units/admin/members/:memberId/role"
  | "/api/units/admin/units"
  | "/api/units/admin/units/:id"
  | "/api/visits"
  | "/api/visits/:id"
  | "/api/visits/:id/assign"
  | "/api/visits/:id/cancel"
  | "/api/visits/:id/complete"
  | "/api/visits/:id/confirm"
  | "/api/visits/:id/jobs"
  | "/api/visits/:id/jobs/:jobId";

type ApiRouteSchema = {
  [Path in ApiRoutePath]: RpcRoute<Path>;
};

export type AppType = Hono<BlankEnv, ApiRouteSchema, "/">;
