// AUTO-GENERATED by scripts/build-trust-store.mjs — do not edit by hand.
//
// Concatenated PEM of the ICP-Brasil trust anchors vendored under
// `trust-store/*.crt` (the official ITI AC-Raiz bundle). Imported (not read
// from disk) so it survives the API's esbuild bundling + `src/` pruning.
export const ICP_BRASIL_TRUST_STORE_PEM = "";
