// Notification Service - Core exports
export {
  sendNotification,
  getRecipientsByRole,
  notifyJobSubmittedForReview,
  notifyJobApproved,
  notifyJobRejected,
  notifyJobAssigned,
  notifyCertificateReady,
  notifyCertificateAmended,
  notifyNCCreated,
  notifyNCEscalatedToCapa,
  notifyCompetenceApproved,
  notifyCompetenceRequested,
  notifyCompetenceExpiring,
  notifyCompetenceExpired,
  notifyAssetDueForRecalibration,
  notifyStandardExpiring,
  notifyStandardExpired,
  notifyJobOverdue,
  notifyPaymentReceived,
  notifyPaymentFailed,
  notifyCalibrationRequestSubmitted,
  notifyCalibrationRequestUnderReview,
  notifyCalibrationRequestApproved,
  notifyCalibrationRequestRejected,
  notifyCalibrationRequestConverted,
  notifyVisitScheduled,
  notifyVisitConfirmed,
  notifyVisitRescheduled,
  notifyVisitCancelled,
  notifyVisitReminder,
  sendPortalDueDigests,
  getLabEmailBrand,
  type PortalDigestRunResult,
  type SendNotificationOptions,
  type NotificationResult,
} from "./service";

// Email suppression / unsubscribe list (issue #577)
export {
  suppressEmail,
  isEmailSuppressed,
  normalizeSuppressionEmail,
  suppressionScopesToCheck,
  type SuppressEmailInput,
  type EmailSuppressionScope,
  type EmailSuppressionReason,
  type EmailSuppressionSource,
} from "./suppression";

// Service-order customer-facing email dispatcher (mini-spec A)
export {
  sendServiceOrderCustomerEmail,
  resolveServiceOrderRecipient,
  type ServiceOrderEmailInput,
  type ServiceOrderEmailRenderContext,
  type ServiceOrderDispatchTarget,
  type CustomerDispatchTarget,
  type ServiceOrderCustomerEmailResult,
} from "./service-order-customer-email";
