export type XlsxTokenKind =
  | 'Texto'
  | 'Data'
  | 'Número'
  | 'Lista'
  | 'URL'
  | 'Imagem'

export interface XlsxTokenCatalogItem {
  group: string
  groupLabel: string
  path: string
  label: string
  description: string
  kind: XlsxTokenKind
  example?: string
}

export const XLSX_TOKEN_CATALOG: XlsxTokenCatalogItem[] = [
  {
    group: 'customer',
    groupLabel: 'Cliente',
    path: 'customer.name',
    label: 'Nome do cliente',
    description: 'Razão social ou nome exibido no certificado.',
    kind: 'Texto',
  },
  {
    group: 'customer',
    groupLabel: 'Cliente',
    path: 'customer.taxId',
    label: 'CNPJ/CPF',
    description: 'Documento fiscal cadastrado para o cliente.',
    kind: 'Texto',
  },
  {
    group: 'customer',
    groupLabel: 'Cliente',
    path: 'customer.address',
    label: 'Endereço',
    description: 'Endereço formatado do cliente.',
    kind: 'Texto',
  },
  {
    group: 'customer',
    groupLabel: 'Cliente',
    path: 'customer.phone',
    label: 'Telefone',
    description: 'Telefone principal do cliente.',
    kind: 'Texto',
  },
  {
    group: 'customer',
    groupLabel: 'Cliente',
    path: 'customer.email',
    label: 'E-mail',
    description: 'E-mail principal do cliente.',
    kind: 'Texto',
  },
  {
    group: 'asset',
    groupLabel: 'Instrumento',
    path: 'asset.kind',
    label: 'Tipo do instrumento',
    description: 'Nome/tipo do ativo calibrado.',
    kind: 'Texto',
  },
  {
    group: 'asset',
    groupLabel: 'Instrumento',
    path: 'asset.serialNumber',
    label: 'Número de série',
    description: 'Série cadastrada no ativo.',
    kind: 'Texto',
  },
  {
    group: 'asset',
    groupLabel: 'Instrumento',
    path: 'asset.tag',
    label: 'Identificação interna',
    description: 'Tag ou código interno do ativo.',
    kind: 'Texto',
  },
  {
    group: 'asset',
    groupLabel: 'Instrumento',
    path: 'asset.model',
    label: 'Modelo',
    description: 'Modelo informado no cadastro do ativo.',
    kind: 'Texto',
  },
  {
    group: 'asset',
    groupLabel: 'Instrumento',
    path: 'asset.manufacturer',
    label: 'Fabricante',
    description: 'Fabricante informado no cadastro do ativo.',
    kind: 'Texto',
  },
  {
    group: 'asset',
    groupLabel: 'Instrumento',
    path: 'asset.measurementUnit',
    label: 'Unidade do instrumento',
    description: 'Unidade base configurada no tipo do instrumento.',
    kind: 'Texto',
  },
  {
    group: 'asset',
    groupLabel: 'Instrumento',
    path: 'asset.capacity',
    label: 'Capacidade',
    description: 'Capacidade no snapshot técnico do ativo.',
    kind: 'Texto',
  },
  {
    group: 'asset',
    groupLabel: 'Instrumento',
    path: 'asset.capacityText',
    label: 'Capacidade formatada',
    description: 'Capacidade com unidade, quando disponível.',
    kind: 'Texto',
  },
  {
    group: 'asset',
    groupLabel: 'Instrumento',
    path: 'asset.division',
    label: 'Divisão/resolução',
    description: 'Resolução no snapshot técnico do ativo.',
    kind: 'Texto',
  },
  {
    group: 'asset',
    groupLabel: 'Instrumento',
    path: 'asset.divisionText',
    label: 'Divisão formatada',
    description: 'Resolução com unidade, quando disponível.',
    kind: 'Texto',
  },
  {
    group: 'certificate',
    groupLabel: 'Certificado',
    path: 'certificate.number',
    label: 'Número do certificado',
    description: 'Identificador do certificado emitido.',
    kind: 'Texto',
  },
  {
    group: 'certificate',
    groupLabel: 'Certificado',
    path: 'certificate.name',
    label: 'Nome do certificado',
    description: 'Nome configurado para o documento emitido.',
    kind: 'Texto',
  },
  {
    group: 'certificate',
    groupLabel: 'Certificado',
    path: 'certificate.issuedAt',
    label: 'Data de emissão',
    description: 'Data/hora da aprovação usada na emissão.',
    kind: 'Data',
  },
  {
    group: 'certificate',
    groupLabel: 'Certificado',
    path: 'certificate.issuedAtText',
    label: 'Data de emissão formatada',
    description: 'Data de emissão no formato dd/mm/aaaa.',
    kind: 'Texto',
  },
  {
    group: 'certificate',
    groupLabel: 'Certificado',
    path: 'certificate.amendmentNumber',
    label: 'Número da emenda',
    description: 'Número da emenda quando o certificado é retificado.',
    kind: 'Texto',
  },
  {
    group: 'job',
    groupLabel: 'Calibração',
    path: 'job.id',
    label: 'ID da calibração',
    description: 'Identificador interno da calibração aprovada.',
    kind: 'Número',
  },
  {
    group: 'job',
    groupLabel: 'Calibração',
    path: 'job.performedAt',
    label: 'Data da calibração',
    description: 'Data/hora em que a calibração foi executada.',
    kind: 'Data',
  },
  {
    group: 'job',
    groupLabel: 'Calibração',
    path: 'job.performedAtText',
    label: 'Data da calibração formatada',
    description: 'Data da calibração no formato dd/mm/aaaa.',
    kind: 'Texto',
  },
  {
    group: 'job',
    groupLabel: 'Calibração',
    path: 'job.location',
    label: 'Local da calibração',
    description: 'Endereço ou local registrado para a execução.',
    kind: 'Texto',
  },
  {
    group: 'method',
    groupLabel: 'Método',
    path: 'method.name',
    label: 'Nome do método',
    description: 'Método aplicado na calibração.',
    kind: 'Texto',
  },
  {
    group: 'method',
    groupLabel: 'Método',
    path: 'method.version',
    label: 'Versão do método',
    description: 'Versão do método no snapshot aprovado.',
    kind: 'Texto',
  },
  {
    group: 'method',
    groupLabel: 'Método',
    path: 'method.procedureCode',
    label: 'Procedimento',
    description: 'Código de procedimento configurado no método.',
    kind: 'Texto',
  },
  {
    group: 'method',
    groupLabel: 'Método',
    path: 'method.referenceStandardsText',
    label: 'Normas de referência',
    description: 'Normas de referência do método em texto.',
    kind: 'Texto',
  },
  {
    group: 'environment',
    groupLabel: 'Ambiente',
    path: 'environment.temperature',
    label: 'Temperatura',
    description: 'Temperatura registrada no snapshot ambiental.',
    kind: 'Número',
  },
  {
    group: 'environment',
    groupLabel: 'Ambiente',
    path: 'environment.temperatureText',
    label: 'Temperatura formatada',
    description: 'Temperatura com unidade.',
    kind: 'Texto',
  },
  {
    group: 'environment',
    groupLabel: 'Ambiente',
    path: 'environment.relativeHumidity',
    label: 'Umidade relativa',
    description: 'Umidade registrada no snapshot ambiental.',
    kind: 'Número',
  },
  {
    group: 'environment',
    groupLabel: 'Ambiente',
    path: 'environment.relativeHumidityText',
    label: 'Umidade formatada',
    description: 'Umidade relativa com unidade.',
    kind: 'Texto',
  },
  {
    group: 'environment',
    groupLabel: 'Ambiente',
    path: 'environment.pressure',
    label: 'Pressão',
    description: 'Pressão registrada no snapshot ambiental.',
    kind: 'Número',
  },
  {
    group: 'environment',
    groupLabel: 'Ambiente',
    path: 'environment.pressureText',
    label: 'Pressão formatada',
    description: 'Pressão com unidade.',
    kind: 'Texto',
  },
  {
    group: 'lab',
    groupLabel: 'Laboratório',
    path: 'lab.name',
    label: 'Nome do laboratório',
    description: 'Nome da organização/unidade emissora.',
    kind: 'Texto',
  },
  {
    group: 'lab',
    groupLabel: 'Laboratório',
    path: 'lab.accreditationNumber',
    label: 'Acreditação',
    description: 'Número de acreditação da unidade emissora.',
    kind: 'Texto',
  },
  {
    group: 'lab',
    groupLabel: 'Laboratório',
    path: 'lab.technicalManagerName',
    label: 'Responsável técnico',
    description: 'Responsável técnico configurado no laboratório.',
    kind: 'Texto',
  },
  {
    group: 'organization',
    groupLabel: 'Organização',
    path: 'organization.logo',
    label: 'Logo da organização',
    description: 'Imagem do logo configurado para a organização.',
    kind: 'Imagem',
  },
  {
    group: 'approval',
    groupLabel: 'Aprovação',
    path: 'approval.approvedBy.name',
    label: 'Aprovador',
    description: 'Nome do usuário que aprovou a calibração.',
    kind: 'Texto',
  },
  {
    group: 'approval',
    groupLabel: 'Aprovação',
    path: 'approval.signatureUrl',
    label: 'Assinatura',
    description: 'Imagem da assinatura visual do aprovador.',
    kind: 'Imagem',
  },
  {
    group: 'service',
    groupLabel: 'Ordem de serviço',
    path: 'serviceOrder.inmetroRepairSealNumber',
    label: 'Lacre de reparo',
    description: 'Número do lacre Inmetro registrado na ordem de serviço.',
    kind: 'Texto',
  },
  {
    group: 'graphics',
    groupLabel: 'Gráficos',
    path: 'graphics.eccentricityIndicator',
    label: 'Indicador de excentricidade',
    description:
      'Imagem dinâmica da posição do indicador, renderizada a partir do método e do instrumento.',
    kind: 'Imagem',
  },
  {
    group: 'tables',
    groupLabel: 'Tabelas',
    path: 'standards',
    label: 'Padrões usados',
    description: 'Lista de padrões de referência disponíveis para tabelas.',
    kind: 'Lista',
  },
  {
    group: 'tables',
    groupLabel: 'Tabelas',
    path: 'calibrationResults',
    label: 'Resultados da calibração',
    description: 'Linhas de resultado normalizadas para blocos/tabelas.',
    kind: 'Lista',
  },
  {
    group: 'tables',
    groupLabel: 'Tabelas',
    path: 'dataDisplay',
    label: 'Dados preenchidos formatados',
    description:
      'Campos do método com números convertidos para a unidade base.',
    kind: 'Lista',
  },
  {
    group: 'tables',
    groupLabel: 'Tabelas',
    path: 'resultsDisplay',
    label: 'Resultados formatados',
    description:
      'Resultados calculados com números convertidos para a unidade base.',
    kind: 'Lista',
  },
  {
    group: 'tables',
    groupLabel: 'Tabelas',
    path: 'uncertaintyBudget',
    label: 'Orçamento de incerteza',
    description: 'Linhas do orçamento de incerteza para tabelas.',
    kind: 'Lista',
  },
]

export const xlsxTokenGroups = [
  { value: 'all', label: 'Todos' },
  ...Array.from(
    new Map(
      XLSX_TOKEN_CATALOG.map((token) => [
        token.group,
        { value: token.group, label: token.groupLabel },
      ]),
    ).values(),
  ),
]
